/** AizanoiOS Workspace — file explorer over the browser-local virtual file system. */
const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ICONS={folder:'📁',text:'📄',image:'🖼️',audio:'🎵',default:'📦'};
function iconFor(node){if(node.kind==='folder')return ICONS.folder;if((node.mime||'').startsWith('text/')||node.mime==='application/json')return ICONS.text;if((node.mime||'').startsWith('image/'))return ICONS.image;if((node.mime||'').startsWith('audio/'))return ICONS.audio;return ICONS.default;}

export function createWorkspaceApp({apps,dialog,filesystem:fs,notifications,sound}){
  return {async mount({container,options}){
    let cwd=options?.folderId||fs.documentsId,menuOpener=null,focusRestoreTimer=null,previewUrl=null,previewNode=null;
    const downloadResources=new Map();
    container.innerHTML=`<div class="az-app-shell"><div class="az-app-toolbar"><strong>Workspace</strong><span class="az-system-spacer"></span><span class="az-app-caption">Local files · stored in this browser</span></div><div class="az-workspace"><div class="az-workspace-actions" role="toolbar" aria-label="Workspace actions"><button class="az-button" type="button" data-ws-up>Up</button><button class="az-button" type="button" data-ws-newfolder>New folder</button><button class="az-button" type="button" data-ws-import>Import files…</button><input type="file" multiple hidden data-ws-file-input><span class="az-system-spacer"></span><span class="az-camera-status" data-ws-path></span></div><div class="az-workspace-grid" data-ws-grid role="list"></div><section class="az-workspace-preview" data-ws-preview hidden aria-label="Image preview"><header><strong data-ws-preview-name>Preview</strong><span class="az-system-spacer"></span><button class="az-button" type="button" data-ws-preview-download>Download</button><button class="az-button" type="button" data-ws-preview-close>Close</button></header><img data-ws-preview-image alt=""></section></div></div>`;
    const grid=container.querySelector('[data-ws-grid]'),pathEl=container.querySelector('[data-ws-path]'),fileInput=container.querySelector('[data-ws-file-input]'),preview=container.querySelector('[data-ws-preview]'),previewImg=container.querySelector('[data-ws-preview-image]'),previewName=container.querySelector('[data-ws-preview-name]');

    async function refresh(){const node=await fs.getNode(cwd);if(!node){cwd=fs.documentsId;return refresh();}const map=await fs.allNodes(),crumbs=[];let cursor=node;while(cursor){crumbs.unshift(cursor);cursor=cursor.parent?map.get(cursor.parent):null;}pathEl.textContent=crumbs.map((crumb)=>crumb.name).join(' / ');const children=await fs.childrenOf(cwd);children.sort((a,b)=>(a.kind===b.kind?a.name.localeCompare(b.name):a.kind==='folder'?-1:1));grid.innerHTML=children.length?children.map((child)=>`<article class="az-workspace-item" data-ws-id="${esc(child.id)}" role="listitem"><button class="az-workspace-open" type="button" data-ws-open="${esc(child.id)}" aria-label="Open ${esc(child.name)}"><span class="az-workspace-icon">${iconFor(child)}</span><strong>${esc(child.name)}</strong><small>${child.kind==='folder'?`${(child.children||[]).length} items`:fs.formatSize(child.size)}</small></button><button class="az-workspace-more" type="button" data-ws-menu="${esc(child.id)}" aria-label="Actions for ${esc(child.name)}">⋯</button></article>`).join(''):'<div class="az-empty-state"><div><h3>This folder is empty</h3><p>Import files, save something from Notepad, or capture a photo.</p></div></div>';}
    function releaseDownloadUrl(url){const timer=downloadResources.get(url);if(timer)clearTimeout(timer);downloadResources.delete(url);URL.revokeObjectURL(url);}
    async function download(node){const blob=await fs.readFileBlob(node.id);if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=node.name;link.click();downloadResources.set(url,setTimeout(()=>releaseDownloadUrl(url),60000));}
    function closePreview(){if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}previewNode=null;preview.hidden=true;previewImg.removeAttribute('src');}
    async function showImagePreview(node){closePreview();const blob=await fs.readFileBlob(node.id);if(!blob)return;previewUrl=URL.createObjectURL(blob);previewNode=node;previewImg.src=previewUrl;previewImg.alt=node.name;previewName.textContent=node.name;preview.hidden=false;preview.scrollIntoView({block:'nearest'});}
    async function openNode(id){const node=await fs.getNode(id);if(!node)return;if(node.kind==='folder'){closePreview();cwd=node.id;await refresh();return;}const mime=node.mime||'';sound.play('click');if(mime.startsWith('text/')||mime==='application/json')apps.open('notepad',{fileId:node.id});else if(mime.startsWith('image/'))await showImagePreview(node);else if(mime.startsWith('audio/'))apps.open('winamp',{trackId:node.id,name:node.name});else await download(node);}

    function closeMenu({restoreFocus=true}={}){if(focusRestoreTimer){clearTimeout(focusRestoreTimer);focusRestoreTimer=null;}const menu=document.querySelector('[data-ws-actionmenu]'),shouldRestore=Boolean(menu);menu?.remove();document.removeEventListener('click',onDocClick,true);document.removeEventListener('keydown',onMenuKey,true);if(restoreFocus&&shouldRestore&&menuOpener?.isConnected){const opener=menuOpener;menuOpener=null;focusRestoreTimer=setTimeout(()=>{focusRestoreTimer=null;if(opener.isConnected)opener.focus();},0);}else menuOpener=null;}
    function onDocClick(event){if(!event.target.closest('[data-ws-actionmenu]'))closeMenu();}
    function onMenuKey(event){if(event.key==='Escape'){event.stopPropagation();closeMenu();}}
    function openMenu(id,anchor){closeMenu();menuOpener=anchor;const menu=document.createElement('div');menu.className='az-dialog az-ws-actionmenu';menu.dataset.wsActionmenu=id;menu.setAttribute('role','menu');menu.setAttribute('aria-label','Actions for item');menu.innerHTML=`<header class="az-dialog-header"><strong>Item actions</strong><span class="az-system-spacer"></span><button class="az-icon-button" type="button" role="menuitem" data-ws-menu-close aria-label="Close menu">×</button></header><div class="az-ws-actionmenu-body"><button class="az-button" type="button" role="menuitem" data-ws-act="rename">Rename</button><button class="az-button" type="button" role="menuitem" data-ws-act="trash">Move to Recycle Bin</button><button class="az-button" type="button" role="menuitem" data-ws-act="cancel">Cancel</button></div>`;const rect=anchor.getBoundingClientRect();Object.assign(menu.style,{position:'fixed',left:`${Math.min(Math.max(8,rect.left),window.innerWidth-270)}px`,top:`${Math.min(rect.bottom+6,window.innerHeight-210)}px`,zIndex:'8600'});document.body.appendChild(menu);menu.querySelector('[data-ws-act="rename"]').focus();menu.addEventListener('click',async(event)=>{if(event.target.closest('[data-ws-menu-close]')){closeMenu();return;}const action=event.target.closest('[data-ws-act]')?.dataset.wsAct;if(!action)return;closeMenu();try{if(action==='rename'){const node=await fs.getNode(id);const name=await dialog.prompt({title:'Rename item',message:'Choose a new name for this Workspace item.',label:'Name',defaultValue:node?.name||'',confirmLabel:'Rename'});if(name){await fs.renameNode(id,name);sound.play('notification');await refresh();}}else if(action==='trash'){const node=await fs.getNode(id);await fs.trashNode(id);sound.play('trash');notifications.notify('Workspace',`${node?.name||'Item'} moved to the Recycle Bin.`,'system');await refresh();}}catch(error){notifications.notify('Workspace',error.message,'error');}});document.addEventListener('click',onDocClick,true);document.addEventListener('keydown',onMenuKey,true);}

    async function click(event){if(event.target.closest('[data-ws-up]')){const node=await fs.getNode(cwd);if(node?.parent){closePreview();cwd=node.parent;await refresh();}return;}if(event.target.closest('[data-ws-newfolder]')){const name=await dialog.prompt({title:'New folder',message:'Create a folder in the current Workspace location.',label:'Folder name',defaultValue:'New folder',confirmLabel:'Create'});if(!name)return;await fs.createFolder({name,parent:cwd});sound.play('notification');return refresh();}if(event.target.closest('[data-ws-import]')){fileInput.click();return;}if(event.target.closest('[data-ws-preview-close]')){closePreview();return;}if(event.target.closest('[data-ws-preview-download]')){if(previewNode)await download(previewNode);return;}const menuAnchor=event.target.closest('[data-ws-menu]');if(menuAnchor){event.stopPropagation();openMenu(menuAnchor.dataset.wsMenu,menuAnchor);return;}const openId=event.target.closest('[data-ws-open]')?.dataset.wsOpen;if(openId)return openNode(openId);}
    async function handleFileChange(){const files=[...(fileInput.files||[])];for(const file of files)await fs.createFile({name:file.name,parent:cwd,blob:file,mime:file.type});fileInput.value='';if(files.length){sound.play('notification');notifications.notify('Workspace',`${files.length} file${files.length===1?'':'s'} imported into ${pathEl.textContent||'the current folder'}.`,'system');}await refresh();}
    const handleClick=(event)=>{click(event).catch((error)=>notifications.notify('Workspace',error.message,'error'));};
    fileInput.addEventListener('change',handleFileChange);container.addEventListener('click',handleClick);await refresh();
    return()=>{closeMenu({restoreFocus:false});closePreview();fileInput.removeEventListener('change',handleFileChange);container.removeEventListener('click',handleClick);for(const url of [...downloadResources.keys()])releaseDownloadUrl(url);};
  }};
}
