import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const base=process.env.ANCIENT_WORLD_BASE_URL||'http://127.0.0.1:4173';
async function withPage(fn){const browser=await chromium.launch({headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});const context=await browser.newContext({viewport:{width:1280,height:860},permissions:['camera','microphone']});const page=await context.newPage(),errors=[];page.on('pageerror',(err)=>errors.push(`pageerror: ${err.message}`));page.on('console',(msg)=>{if(msg.type()==='error')errors.push(`console: ${msg.text()}`);});await page.goto(`${base}/?workspace-qa=${Date.now()}`,{waitUntil:'networkidle'});await page.evaluate(()=>{indexedDB.deleteDatabase('aizanoi-workspace');localStorage.clear();});await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(900);try{await fn(page,errors);}finally{await browser.close();}assert.deepEqual(errors,[],`page errors: ${JSON.stringify(errors)}`);}
async function openApp(page,id){await page.evaluate((appId)=>window.AIZANOI_OS.openApp(appId),id);const body=page.locator(`.az-window[data-app-id="${id}"] [data-app-body]`);await body.waitFor({state:'visible'});await page.waitForFunction((appId)=>{const host=document.querySelector(`.az-window[data-app-id="${appId}"] [data-app-body]`);return Boolean(host)&&!host.textContent.includes('Opening application…')&&!host.hasAttribute('data-app-mounting');},id);await page.waitForTimeout(100);}
async function waitWorkspacePath(page,value='Workspace'){await page.waitForFunction((expected)=>document.querySelector('[data-ws-path]')?.textContent?.trim()===expected,value);}
async function answerPrompt(page,value){await page.locator('[data-app-prompt-input]').waitFor({state:'visible'});await page.fill('[data-app-prompt-input]',value);await page.click('[data-app-prompt-ok]');}
async function seedText(page,name,parent='folder-documents'){return page.evaluate(async({fileName,parentId})=>{const fs=await import('/js/v3/workspace/fs.js');return(await fs.createFile({name:fileName,parent:parentId,blob:new Blob(['x'],{type:'text/plain'}),mime:'text/plain'})).id;},{fileName:name,parentId:parent});}

test('Workspace root, nested restore and current-folder imports are coherent',async()=>withPage(async(page)=>{await openApp(page,'workspace');await page.click('[data-ws-up]');await waitWorkspacePath(page);await page.click('[data-ws-newfolder]');await answerPrompt(page,'My Custom Root Folder');await page.waitForTimeout(250);assert.match(await page.locator('.az-workspace-grid').innerText(),/My Custom Root Folder/);await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(800);await openApp(page,'workspace');await page.click('[data-ws-up]');await waitWorkspacePath(page);assert.match(await page.locator('.az-workspace-grid').innerText(),/Text|My Custom Root Folder/);await page.locator('.az-workspace-item',{hasText:'Text'}).first().click();await waitWorkspacePath(page,'Workspace / Text');await page.click('[data-ws-newfolder]');await answerPrompt(page,'Nested Projects');await page.locator('.az-workspace-item',{hasText:'Nested Projects'}).first().click();await waitWorkspacePath(page,'Workspace / Text / Nested Projects');const path=await page.locator('[data-ws-path]').innerText();assert.match(path,/Nested Projects/);const chooserPromise=page.waitForEvent('filechooser');await page.click('[data-ws-import]');const chooser=await chooserPromise;await chooser.setFiles([{name:'inside.txt',mimeType:'text/plain',buffer:Buffer.from('inside')}]);await page.waitForTimeout(250);assert.match(await page.locator('.az-workspace-grid').innerText(),/inside.txt/);const fileId=await page.evaluate(async()=>{const fs=await import('/js/v3/workspace/fs.js');const docs=await fs.childrenOf(fs.DOCUMENTS_ID),nested=docs.find((n)=>n.name==='Nested Projects'),files=await fs.childrenOf(nested.id);return files.find((n)=>n.name==='inside.txt').id;});await page.evaluate(async(id)=>(await import('/js/v3/workspace/fs.js')).trashNode(id),fileId);await openApp(page,'recycle-bin');await page.click(`[data-bin-restore="${fileId}"]`);const restored=await page.evaluate(async(id)=>{const fs=await import('/js/v3/workspace/fs.js'),docs=await fs.childrenOf(fs.DOCUMENTS_ID),nested=docs.find((n)=>n.name==='Nested Projects');return(await fs.childrenOf(nested.id)).some((n)=>n.id===id);},fileId);assert.equal(restored,true);}));

test('Workspace image files preview locally instead of opening Camera or auto-downloading',async()=>withPage(async(page)=>{await page.evaluate(async()=>{const fs=await import('/js/v3/workspace/fs.js'),bytes=new Uint8Array([137,80,78,71,13,10,26,10]);await fs.createFile({name:'preview.png',parent:fs.PICTURES_ID,blob:new Blob([bytes],{type:'image/png'}),mime:'image/png'});});await openApp(page,'workspace');await page.locator('.az-workspace-item',{hasText:'Photos'}).first().click();await waitWorkspacePath(page,'Workspace / Photos');await page.locator('.az-workspace-item',{hasText:'preview.png'}).first().click();await page.locator('[data-ws-preview]').waitFor({state:'visible'});assert.equal(await page.locator('[data-ws-preview-name]').innerText(),'preview.png');assert.equal(await page.evaluate(()=>Boolean(document.querySelector('.az-window[data-app-id="camera"]'))),false);}));

test('Workspace action menu is canonical and restores opener focus',async()=>withPage(async(page)=>{await seedText(page,'menu-item.txt');await openApp(page,'workspace');await page.click('.az-workspace-more');const menu=page.locator('[data-ws-actionmenu]');await menu.waitFor({state:'visible'});assert.equal(await menu.getAttribute('role'),'menu');assert.deepEqual(await menu.locator('[data-ws-act]').evaluateAll((nodes)=>nodes.map((n)=>n.dataset.wsAct)),['rename','trash','cancel']);assert.equal(await menu.evaluate((node)=>node.classList.contains('az-w98-dialog')),false);await page.keyboard.press('Escape');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.activeElement?.classList?.contains('az-workspace-more')),true);}));

test('Notepad accepts real pointer focus and keyboard typing before its unsaved flow',async()=>withPage(async(page)=>{await openApp(page,'notepad');assert.equal((await page.locator('[data-note-status]').innerText()).trim(),'New document');const editor=page.locator('[data-note-text]');await editor.click();assert.equal(await editor.evaluate((node)=>document.activeElement===node),true,'clicking the editor must keep textarea focus');await page.keyboard.type('hello workspace contract');assert.equal(await editor.inputValue(),'hello workspace contract');await page.click('[data-note-action="save"]');await answerPrompt(page,'contract-note.txt');await page.waitForTimeout(200);assert.match(await page.locator('[data-note-status]').innerText(),/Saved/);await editor.click();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.type('changed');assert.equal(await editor.inputValue(),'changed');await page.evaluate(()=>window.AIZANOI_OS.closeApp('notepad'));await page.locator('[data-az-app-dialog]').waitFor({state:'visible'});assert.equal(await page.locator('[data-app-dialog-value="cancel"]').evaluate((node)=>document.activeElement===node),true);await page.click('[data-app-dialog-value="cancel"]');assert.equal(await page.evaluate(()=>Boolean(document.querySelector('[data-note-text]'))),true);}));

test('Camera cleanup stops media tracks and revokes gallery URLs',async()=>withPage(async(page)=>{await page.addInitScript(()=>{window.__qaLiveTracks=[];const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=async(constraints)=>{const stream=await original(constraints);window.__qaLiveTracks.push(...stream.getTracks());return stream;};});await page.reload({waitUntil:'networkidle'});await page.evaluate(async()=>{const fs=await import('/js/v3/workspace/fs.js');await fs.createFile({name:'qa-photo.png',parent:fs.PICTURES_ID,blob:new Blob([new Uint8Array([1,2,3])],{type:'image/png'}),mime:'image/png'});});await openApp(page,'camera');await page.click('[data-cam-start]');await page.waitForTimeout(500);const urls=await page.locator('img[data-photo-src]').count();await page.evaluate(()=>{window.__qaRevoked=[];const original=URL.revokeObjectURL.bind(URL);URL.revokeObjectURL=(url)=>{window.__qaRevoked.push(url);return original(url);};});await page.evaluate(()=>window.AIZANOI_OS.closeApp('camera'));await page.waitForTimeout(250);const state=await page.evaluate(()=>({live:window.__qaLiveTracks.filter((track)=>track.readyState==='live').length,revoked:window.__qaRevoked.length}));assert.equal(state.live,0);assert.ok(state.revoked>=urls);}));

test('Winamp persists Workspace tracks, prunes stale entries and exposes playlist controls',async()=>withPage(async(page)=>{await openApp(page,'winamp');const chooserPromise=page.waitForEvent('filechooser');await page.click('[data-wa-add-local]');const chooser=await chooserPromise;await chooser.setFiles([{name:'qa-tone.mp3',mimeType:'audio/mpeg',buffer:Buffer.from('not-real-audio')}]);await page.waitForTimeout(300);assert.match(await page.locator('[data-wa-playlist]').innerText(),/qa-tone.mp3/);assert.equal(await page.locator('[data-wa-remove]').count(),1);assert.equal(await page.locator('[data-wa-move-up]').count(),1);await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(700);await openApp(page,'winamp');assert.match(await page.locator('[data-wa-playlist]').innerText(),/qa-tone.mp3/);await page.evaluate(async()=>{const fs=await import('/js/v3/workspace/fs.js'),items=await fs.childrenOf(fs.MUSIC_ID),track=items.find((n)=>n.name==='qa-tone.mp3');if(track)await fs.deleteNode(track.id);});await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(700);await openApp(page,'winamp');assert.doesNotMatch(await page.locator('[data-wa-playlist]').innerText(),/qa-tone.mp3/);}));