'use strict';
importScripts('/release.js');
const CACHE=self.AIZANOI_RELEASE.CACHE;
const MAX_RUNTIME_ENTRIES=128;
/* Retired product surfaces. A visitor who loaded one of these before its retirement may still hold the response in a pre-cleanup runtime cache. They must not survive the release transition, and must never be served as an offline fallback. Keep this list append-only: a retired path never comes back. */
const RETIRED_PATHS=['/analytics/dashboards/hr-analytics-full-set'];
function isRetiredPath(pathname){for(const prefix of RETIRED_PATHS)if(pathname===prefix||pathname.startsWith(prefix+'/')||pathname.startsWith(prefix+'.'))return true;return false;}
/* Offline SLA: the shell/home and Worlds portal are guaranteed after install. Lazy product/app modules and standalone products become offline-capable after first successful use through runtime caching. */
const PRECACHE=['/','/worlds/','/release.js','/manifest.webmanifest','/assets/branding/aizanoi-logo-mark.svg','/assets/branding/aizanoi-pwa-192.png','/assets/branding/aizanoi-pwa-512.png','/assets/branding/aizanoi-pwa-maskable-512.png','/assets/wallpapers/aizanoi-os-sunrise.svg','/styles/tokens.css','/styles/base.css','/styles/shell.css','/styles/components.css','/styles/device-shell.css','/js/v3/main.js','/js/v3/aizanoi-os.js','/js/v3/brand-platform.js','/js/v3/registry.js','/js/v3/module-registry.generated.js','/js/v3/store.js','/js/v3/shell.js','/news/index.json'];
const PRECACHE_KEYS=new Set(PRECACHE);let pruneQueue=Promise.resolve();
async function precacheShell(){const cache=await caches.open(CACHE),responses=await Promise.all(PRECACHE.map(async(url)=>{const response=await fetch(new Request(url,{cache:'reload'}));if(!response.ok)throw new Error(`Precache failed for ${url}: ${response.status}`);return[url,response];}));await Promise.all(responses.map(([url,response])=>cache.put(url,response)));}
self.addEventListener('install',(event)=>event.waitUntil(precacheShell().then(()=>self.skipWaiting())));
async function retireSupersededCaches(){const keys=await caches.keys();await Promise.all(keys.filter((key)=>(key.startsWith('aizanoi-field-shell-')||key.startsWith('aizanoi-os-shell-'))&&key!==CACHE).map((key)=>caches.delete(key)));}async function purgeRetiredEntries(){for(const key of await caches.keys()){const cache=await caches.open(key);for(const request of await cache.keys())if(isRetiredPath(new URL(request.url).pathname))await cache.delete(request);}}
self.addEventListener('activate',(event)=>event.waitUntil(retireSupersededCaches().then(()=>purgeRetiredEntries()).then(()=>self.clients.claim())));
function sameOriginStatic(request){const url=new URL(request.url);return request.method==='GET'&&url.origin===self.location.origin&&/\.(?:css|js|mjs|json|svg|png|jpg|jpeg|webp|gif|woff2?)$/i.test(url.pathname);}
function requestCacheKey(request){const url=new URL(request.url);return`${url.pathname}${url.search}`;}
async function pruneRuntimeCache(){const cache=await caches.open(CACHE),keys=await cache.keys(),runtime=keys.filter((key)=>!PRECACHE_KEYS.has(requestCacheKey(key))),excess=runtime.length-MAX_RUNTIME_ENTRIES;if(excess<=0)return;for(const key of runtime.slice(0,excess))await cache.delete(key);}
function schedulePrune(){pruneQueue=pruneQueue.then(pruneRuntimeCache,pruneRuntimeCache);return pruneQueue;}
async function cacheNavigation(request,response){if(!response.ok)return;if(isRetiredPath(new URL(request.url).pathname))return;const cache=await caches.open(CACHE);await cache.put(request,response.clone());await schedulePrune();}
async function networkFirstStatic(request){const cache=await caches.open(CACHE);try{const response=await fetch(request);if(response.ok)await cache.put(request,response.clone());if(response.ok)await schedulePrune();return response;}catch(error){const cached=await cache.match(request);if(cached)return cached;throw error;}}
async function networkFirstNavigation(request){const url=new URL(request.url);try{const response=await fetch(request);await cacheNavigation(request,response);return response;}catch(error){if(isRetiredPath(url.pathname))throw error;const cached=await caches.match(request);return cached||(url.pathname.startsWith('/worlds/')?caches.match('/worlds/'):caches.match('/'));}}
self.addEventListener('fetch',(event)=>{const request=event.request,url=new URL(request.url);if(request.method!=='GET'||url.pathname.startsWith('/api/'))return;if(request.mode==='navigate'){event.respondWith(networkFirstNavigation(request));return;}if(sameOriginStatic(request))event.respondWith(networkFirstStatic(request));});
