/** Winamp-inspired local player. Workspace tracks remain browser-local. */
const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PLAYLIST_KEY='aizanoi-winamp-playlist-v1';
function readPersisted(){try{const value=JSON.parse(localStorage.getItem(PLAYLIST_KEY));return Array.isArray(value)?value:[];}catch(_){return[];}}
export async function mountWinamp({container,capabilities}){
  const {filesystem,notifications,sound}=capabilities;
  container.innerHTML=`<div class="az-app-shell az-utility-shell az-winamp-shell"><div class="az-winamp"><div class="az-winamp-brand"><strong>WINAMP</strong><span>Local + Workspace audio</span></div><div class="az-winamp-display"><div class="az-winamp-track" data-wa-track>— nothing playing —</div><div class="az-winamp-time" data-wa-time>00:00 / 00:00</div></div><div class="az-winamp-progress"><input type="range" min="0" max="1000" value="0" data-wa-seek aria-label="Seek"></div><div class="az-winamp-controls" role="toolbar" aria-label="Playback controls"><button class="az-button" type="button" data-wa-prev title="Previous">⏮</button><button class="az-button" type="button" data-wa-play title="Play">▶</button><button class="az-button" type="button" data-wa-pause title="Pause">⏸</button><button class="az-button" type="button" data-wa-stop title="Stop">⏹</button><button class="az-button" type="button" data-wa-next title="Next">⏭</button><span class="az-system-spacer"></span><label class="az-winamp-vol">Vol <input type="range" min="0" max="100" value="80" data-wa-vol aria-label="Volume"></label></div><div class="az-winamp-add"><button class="az-button" type="button" data-wa-add-local>Add local files…</button><button class="az-button" type="button" data-wa-add-workspace>Load Workspace · Music</button><button class="az-button" type="button" data-wa-clear>Clear playlist</button><input type="file" accept="audio/*" multiple hidden data-wa-file-input></div><ol class="az-winamp-playlist" data-wa-playlist aria-label="Playlist"></ol><audio data-wa-audio preload="metadata"></audio></div></div>`;
  const audio=container.querySelector('[data-wa-audio]'),trackEl=container.querySelector('[data-wa-track]'),timeEl=container.querySelector('[data-wa-time]'),seekEl=container.querySelector('[data-wa-seek]'),playlistEl=container.querySelector('[data-wa-playlist]'),fileInput=container.querySelector('[data-wa-file-input]'),vol=container.querySelector('[data-wa-vol]');
  let playlist=readPersisted(),index=-1;const localBlobs=new Map();
  function persist(){try{localStorage.setItem(PLAYLIST_KEY,JSON.stringify(playlist.filter((item)=>item.source==='workspace')));}catch(_){}}
  function fmt(seconds){if(!Number.isFinite(seconds)||seconds<0)return'00:00';const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
  function updateTime(){timeEl.textContent=`${fmt(audio.currentTime)} / ${fmt(audio.duration)}`;seekEl.value=audio.duration?String(Math.round(audio.currentTime/audio.duration*1000)):'0';}
  function renderPlaylist(){playlistEl.innerHTML=playlist.length?playlist.map((item,i)=>`<li class="az-winamp-row${i===index?' is-active':''}"><button class="az-winamp-item" type="button" data-wa-item="${i}" aria-label="Play ${esc(item.name)}"><span>${i+1}.</span><strong>${esc(item.name)}</strong></button><span class="az-winamp-row-actions"><button type="button" data-wa-move-up="${i}" aria-label="Move ${esc(item.name)} up" ${i===0?'disabled':''}>↑</button><button type="button" data-wa-move-down="${i}" aria-label="Move ${esc(item.name)} down" ${i===playlist.length-1?'disabled':''}>↓</button><button type="button" data-wa-remove="${i}" aria-label="Remove ${esc(item.name)}">×</button></span></li>`).join(''):'<li class="az-winamp-empty">Playlist empty — add local files or load Workspace · Music.</li>';}
  async function pruneMissing(){const checked=await Promise.all(playlist.map(async(item)=>item.source!=='workspace'||await filesystem.getNode(item.id)?item:null));const next=checked.filter(Boolean);if(next.length!==playlist.length){playlist=next;persist();}}
  async function resolveSource(item){if(item.source==='local')return localBlobs.get(item.localKey)||null;return filesystem.readFileBlob(item.id);}
  function revokeActiveUrl(){if(audio.dataset.blobUrl){URL.revokeObjectURL(audio.dataset.blobUrl);delete audio.dataset.blobUrl;}}
  function stopActive(){audio.pause();audio.removeAttribute('src');audio.load();revokeActiveUrl();index=-1;trackEl.textContent='— nothing playing —';updateTime();renderPlaylist();}
  function removeAt(i,{notify=true}={}){if(i<0||i>=playlist.length)return;const [removed]=playlist.splice(i,1);if(removed.source==='local')localBlobs.delete(removed.localKey);if(i===index)stopActive();else if(i<index)index--;persist();renderPlaylist();if(notify)notifications.notify('Winamp',`${removed.name} removed from the playlist.`,'system');}
  function moveAt(i,delta){const next=i+delta;if(i<0||next<0||i>=playlist.length||next>=playlist.length)return;const current=playlist[index];[playlist[i],playlist[next]]=[playlist[next],playlist[i]];index=current?playlist.indexOf(current):-1;persist();renderPlaylist();}
  async function play(i){if(!playlist.length){notifications.notify('Winamp','Playlist is empty. Add an audio file first.','system');return;}index=(i+playlist.length)%playlist.length;const item=playlist[index],blob=await resolveSource(item);if(!blob){const staleName=item.name;removeAt(index,{notify:false});notifications.notify('Winamp',`${staleName} is no longer available and was removed from the playlist.`,'error');if(playlist.length)return play(Math.min(index,playlist.length-1));return;}const url=URL.createObjectURL(blob);revokeActiveUrl();audio.dataset.blobUrl=url;audio.src=url;trackEl.textContent=`${index+1}. ${item.name}`;updateTime();try{await audio.play();}catch(error){if(error?.name!=='NotAllowedError')notifications.notify('Winamp',`Could not play ${item.name}.`,'error');else notifications.notify('Winamp','Press play again after interacting with the page.','system');}renderPlaylist();}
  async function resumePlayback(){if(!playlist.length){notifications.notify('Winamp','Playlist is empty. Add an audio file first.','system');return;}if(index<0||!audio.getAttribute('src'))return play(index<0?0:index);try{await audio.play();}catch(_){notifications.notify('Winamp','The browser blocked playback. Press play again after interacting with the page.','system');}}
  async function handleAction(event){const playIndex=event.target.closest('[data-wa-item]')?.dataset.waItem;if(playIndex!==undefined)return play(Number(playIndex));const remove=event.target.closest('[data-wa-remove]')?.dataset.waRemove;if(remove!==undefined){sound.play('click');removeAt(Number(remove));return;}const up=event.target.closest('[data-wa-move-up]')?.dataset.waMoveUp;if(up!==undefined){sound.play('click');moveAt(Number(up),-1);return;}const down=event.target.closest('[data-wa-move-down]')?.dataset.waMoveDown;if(down!==undefined){sound.play('click');moveAt(Number(down),1);return;}const action=event.target.closest('[data-wa-play]')?'play':event.target.closest('[data-wa-pause]')?'pause':event.target.closest('[data-wa-stop]')?'stop':event.target.closest('[data-wa-prev]')?'prev':event.target.closest('[data-wa-next]')?'next':event.target.closest('[data-wa-add-local]')?'add-local':event.target.closest('[data-wa-add-workspace]')?'add-ws':event.target.closest('[data-wa-clear]')?'clear':'';if(!action)return;sound.play('click');if(action==='play')return resumePlayback();if(action==='pause')audio.pause();else if(action==='stop'){audio.pause();audio.currentTime=0;}else if(action==='prev')return play(index<0?playlist.length-1:index-1);else if(action==='next')return play(index<0?0:index+1);else if(action==='add-local')fileInput.click();else if(action==='clear'){playlist=[];persist();stopActive();}else if(action==='add-ws'){const items=await filesystem.childrenOf(filesystem.musicId),tracks=items.filter((node)=>node.kind==='file'&&(node.mime||'').startsWith('audio/'));if(!tracks.length){notifications.notify('Winamp','No audio files in Workspace · Music yet.','system');return;}const existing=new Set(playlist.filter((item)=>item.source==='workspace').map((item)=>item.id));for(const node of tracks)if(!existing.has(node.id))playlist.push({source:'workspace',id:node.id,name:node.name});persist();renderPlaylist();if(index<0)return play(0);}}
  const handleClick=(event)=>handleAction(event).catch((error)=>notifications.notify('Winamp',error.message,'error'));
  async function handleFileChange(){const files=[...(fileInput.files||[])],first=playlist.length;for(const file of files){try{const node=await filesystem.createFile({name:file.name,parent:filesystem.musicId,blob:file,mime:file.type||'audio/mpeg'});playlist.push({source:'workspace',id:node.id,name:node.name});}catch(_){const localKey=`local-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;localBlobs.set(localKey,file);playlist.push({source:'local',localKey,name:file.name});}}fileInput.value='';persist();renderPlaylist();if(index===-1&&files.length)await play(first);}
  function handleSeekInput(){if(audio.duration)audio.currentTime=Number(seekEl.value)/1000*audio.duration;}function handleEnded(){play(index+1).catch((error)=>notifications.notify('Winamp',error.message,'error'));}function handleVolumeInput(){audio.volume=Number(vol.value)/100;}function handleAudioError(){if(index>=0){const name=playlist[index]?.name||'track';trackEl.textContent=`Playback error · ${name}`;notifications.notify('Winamp',`The browser could not decode ${name}.`,'error');}}
  container.addEventListener('click',handleClick);fileInput.addEventListener('change',handleFileChange);seekEl.addEventListener('input',handleSeekInput);audio.addEventListener('timeupdate',updateTime);audio.addEventListener('loadedmetadata',updateTime);audio.addEventListener('durationchange',updateTime);audio.addEventListener('ended',handleEnded);audio.addEventListener('error',handleAudioError);vol.addEventListener('input',handleVolumeInput);audio.volume=.8;await pruneMissing();renderPlaylist();updateTime();
  function onOpen(newOptions){const trackId=newOptions?.trackId;if(!trackId)return;const existing=playlist.findIndex((item)=>item.source==='workspace'&&item.id===trackId);if(existing>=0){play(existing).catch((error)=>notifications.notify('Winamp',error.message,'error'));return;}playlist.push({source:'workspace',id:trackId,name:newOptions?.name||'Workspace track'});persist();renderPlaylist();play(playlist.length-1).catch((error)=>notifications.notify('Winamp',error.message,'error'));}
  return{cleanup(){container.removeEventListener('click',handleClick);fileInput.removeEventListener('change',handleFileChange);seekEl.removeEventListener('input',handleSeekInput);audio.removeEventListener('timeupdate',updateTime);audio.removeEventListener('loadedmetadata',updateTime);audio.removeEventListener('durationchange',updateTime);audio.removeEventListener('ended',handleEnded);audio.removeEventListener('error',handleAudioError);vol.removeEventListener('input',handleVolumeInput);audio.pause();revokeActiveUrl();},onOpen};
}
