import * as Archive from '../archive-store.js';

const escapeHtml=(value)=>String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatBytes=(bytes)=>{const n=Math.max(0,Number(bytes)||0);if(n<1024)return`${n} B`;if(n<1024*1024)return`${(n/1024).toFixed(n>10240?0:1)} KB`;return`${(n/1024/1024).toFixed(1)} MB`;};
const shortDate=(value)=>{try{return new Date(Number(value)||Date.now()).toLocaleDateString([],{month:'short',day:'numeric',year:'numeric'});}catch(_){return'';}};
const evidence=(level)=>level?`<span class="az-evidence" data-level="${escapeHtml(level)}">${escapeHtml(level)}</span>`:'';

function metadata(record) {
  const meta=record?.meta||{};
  const rows=[['Type',record?.kind],['Collection',record?.collection],['Place',meta.place],['Period',meta.period],['Source',meta.source],['Rights',meta.rights],['Size',formatBytes(record?.size)],['Updated',shortDate(record?.updatedAt)],['Tags',Array.isArray(meta.tags)?meta.tags.join(', '):'']].filter(([,value])=>value);
  return `<h3>${escapeHtml(meta.title||record?.name||'Record')}</h3><p>${escapeHtml(record?.name||'')}</p>${evidence(meta.evidence)}<dl class="az-meta-list" style="margin-top:14px">${rows.map(([key,value])=>`<div><dt>${escapeHtml(key)}</dt><dd>${escapeHtml(value)}</dd></div>`).join('')}</dl>`;
}

async function mountArchive(container,{api,options}) {
  let collection='All'; let query=''; let selectedId=options?.recordId||null; let destroyed=false;
  const fileInput=document.createElement('input');fileInput.type='file';fileInput.multiple=true;fileInput.hidden=true;fileInput.accept='.csv,.json,.pdf,.md,.txt,.png,.jpg,.jpeg,.webp,.gif,.svg';container.appendChild(fileInput);

  async function draw(){
    if(destroyed)return;const all=await Archive.all();if(destroyed)return;
    const counts=Object.fromEntries(Archive.COLLECTIONS.map((name)=>[name,all.filter((item)=>item.collection===name).length]));
    const filtered=all.filter((item)=>(collection==='All'||item.collection===collection)&&(!query||[item.name,item.kind,item.meta?.place,item.meta?.period,item.meta?.source,...(item.meta?.tags||[])].join(' ').toLowerCase().includes(query.toLowerCase())));
    if(!selectedId||!all.some((item)=>item.id===selectedId))selectedId=filtered[0]?.id||all[0]?.id||null;
    const selected=all.find((item)=>item.id===selectedId)||null;
    container.innerHTML=`<div class="az-app-shell"><div class="az-app-toolbar"><input type="search" data-archive-search value="${escapeHtml(query)}" placeholder="Search records, places, tags…" aria-label="Search Field Archive"><span class="az-system-spacer"></span><button class="az-button" type="button" data-archive-new>New note</button><button class="az-button az-button-primary" type="button" data-archive-import>Import files</button></div><div class="az-archive-layout"><nav class="az-collection-nav" aria-label="Archive collections"><h3>Collections</h3>${['All',...Archive.COLLECTIONS].map((name)=>`<button class="az-collection-button${collection===name?' is-active':''}" type="button" data-collection="${escapeHtml(name)}"><span>${escapeHtml(name)}</span><span>${name==='All'?all.length:counts[name]||0}</span></button>`).join('')}</nav><main class="az-record-stage">${filtered.length?`<div class="az-record-grid">${filtered.map((item)=>`<button class="az-record-card${item.id===selectedId?' is-selected':''}" type="button" data-record="${escapeHtml(item.id)}"><img src="${escapeHtml(Archive.iconFor(item))}" alt=""><span class="az-record-kind">${escapeHtml(item.kind)}</span><strong>${escapeHtml(item.meta?.title||item.name)}</strong><small>${escapeHtml(item.meta?.place||item.collection)} · ${shortDate(item.updatedAt)}</small></button>`).join('')}</div>`:`<div class="az-empty-state"><div><h3>${all.length?'No matching records':'Your field archive is ready'}</h3><p>${all.length?'Try another collection or search.':'Start with the sample Aizanoi record or import your own research material.'}</p><button class="az-button az-button-primary" type="button" data-archive-import>Import records</button></div></div>`}</main><aside class="az-inspector">${selected?metadata(selected)+`<div class="az-inspector-actions"><button class="az-button az-button-teal" type="button" data-open-record="${escapeHtml(selected.id)}">Open</button><button class="az-button" type="button" data-note-record="${escapeHtml(selected.id)}">Add field note</button></div>`:'<p>Select a record to inspect metadata.</p>'}</aside></div></div>`;
    container.appendChild(fileInput);
  }

  const click=async(event)=>{
    const c=event.target.closest('[data-collection]')?.dataset.collection;if(c){collection=c;await draw();return;}
    const record=event.target.closest('[data-record]')?.dataset.record;if(record){selectedId=record;await draw();return;}
    if(event.target.closest('[data-archive-import]')){fileInput.click();return;}
    if(event.target.closest('[data-archive-new]')){api.openApp('notes',{newNote:true});return;}
    const open=event.target.closest('[data-open-record]')?.dataset.openRecord;if(open){api.openRecord(await Archive.get(open));return;}
    const note=event.target.closest('[data-note-record]')?.dataset.noteRecord;if(note){const item=await Archive.get(note);const created=await Archive.createNote(`Observation — ${item.meta?.title||item.name}`,`# Observation — ${item.meta?.title||item.name}\n\nLinked record: ${item.name}\nPlace: ${item.meta?.place||'—'}\nPeriod: ${item.meta?.period||'—'}\nSource: ${item.meta?.source||'—'}\n\n## Observation\n\n`,{place:item.meta?.place||'',period:item.meta?.period||'',source:item.meta?.source||'',evidence:'documented',tags:['field-note',...(item.meta?.tags||[]).slice(0,5)]});api.openApp('notes',{recordId:created.id});}
  };
  const input=(event)=>{if(event.target.matches('[data-archive-search]')){query=event.target.value;clearTimeout(input.timer);input.timer=setTimeout(draw,120);}};
  const files=async()=>{if(!fileInput.files?.length)return;const imported=await Archive.importFiles(fileInput.files);fileInput.value='';api.notify('Field Archive updated',`${imported.length} item${imported.length===1?'':'s'} added locally.`,'archive');await draw();};
  const changed=()=>draw();
  container.addEventListener('click',click);container.addEventListener('input',input);fileInput.addEventListener('change',files);window.addEventListener('aizanoi:archive-change',changed);await draw();
  return()=>{destroyed=true;clearTimeout(input.timer);container.removeEventListener('click',click);container.removeEventListener('input',input);fileInput.removeEventListener('change',files);window.removeEventListener('aizanoi:archive-change',changed);};
}

const TEMPLATES={
  observation:{name:'Field Observation',body:'# Field Observation\n\n## Place / context\n\n## Observation\n\n## Evidence\n\n## Questions\n\n'},
  hypothesis:{name:'Reconstruction Hypothesis',body:'# Reconstruction Hypothesis\n\n## Claim\n\n## Supporting evidence\n\n## Inference / uncertainty\n\n## What would change this?\n\n'},
  source:{name:'Source Review',body:'# Source Review\n\n## Citation\n\n## Main claims\n\n## Evidence quality\n\n## Relevance to reconstruction\n\n'}
};

async function mountNotes(container,{api,options}) {
  let selectedId=options?.recordId||null;let timer=null;let destroyed=false;
  if(options?.newNote){const t=TEMPLATES.observation;const note=await Archive.createNote(`${t.name} ${new Date().toLocaleDateString()}`,t.body,{evidence:'documented',tags:['field-note']});selectedId=note.id;}
  async function ensureNote(){const all=await Archive.all();let notes=all.filter((i)=>i.kind==='note');if(!notes.length){const created=await Archive.createNote('First Field Observation',TEMPLATES.observation.body,{evidence:'documented',tags:['field-note']});notes=[created];}if(!selectedId||!notes.some((i)=>i.id===selectedId))selectedId=notes[0].id;return notes;}
  async function draw(){if(destroyed)return;const notes=await ensureNote();const selected=notes.find((i)=>i.id===selectedId);container.innerHTML=`<div class="az-app-shell"><div class="az-app-toolbar"><select data-note-template aria-label="New note template"><option value="">New from template…</option>${Object.entries(TEMPLATES).map(([id,t])=>`<option value="${id}">${escapeHtml(t.name)}</option>`).join('')}</select><span class="az-system-spacer"></span><span class="az-note-status" data-note-global-status>LOCAL AUTOSAVE</span></div><div class="az-notes-layout"><nav class="az-note-list" aria-label="Field notes">${notes.map((note)=>`<button type="button" class="${note.id===selectedId?'is-active':''}" data-note-id="${escapeHtml(note.id)}"><strong>${escapeHtml(note.meta?.title||note.name.replace(/\.md$/i,''))}</strong><small>${shortDate(note.updatedAt)} · ${escapeHtml(note.meta?.place||'Field note')}</small></button>`).join('')}</nav><section class="az-note-editor"><header class="az-note-editor-head"><input class="az-note-title" data-note-title value="${escapeHtml(selected.meta?.title||selected.name.replace(/\.md$/i,''))}" aria-label="Note title"><span class="az-note-status" data-note-status>Saved locally</span></header><textarea class="az-note-text" data-note-text spellcheck="true" aria-label="Field note content">${escapeHtml(selected.text||'')}</textarea></section></div></div>`;}
  async function save(){const title=container.querySelector('[data-note-title]')?.value.trim()||'Untitled field note';const text=container.querySelector('[data-note-text]')?.value||'';const current=await Archive.get(selectedId);if(!current)return;await Archive.put({...current,name:`${title}.md`,text,size:new Blob([text]).size,meta:{...current.meta,title}});const status=container.querySelector('[data-note-status]');if(status)status.textContent=`Saved ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;}
  const click=async(event)=>{const id=event.target.closest('[data-note-id]')?.dataset.noteId;if(id){await save();selectedId=id;await draw();}};
  const input=(event)=>{if(event.target.matches('[data-note-title],[data-note-text]')){const status=container.querySelector('[data-note-status]');if(status)status.textContent='Saving…';clearTimeout(timer);timer=setTimeout(save,550);}};
  const change=async(event)=>{if(event.target.matches('[data-note-template]')&&event.target.value){await save();const t=TEMPLATES[event.target.value];const note=await Archive.createNote(`${t.name} ${new Date().toLocaleDateString()}`,t.body,{evidence:'documented',tags:['field-note']});selectedId=note.id;await draw();}};
  container.addEventListener('click',click);container.addEventListener('input',input);container.addEventListener('change',change);await draw();
  return async()=>{destroyed=true;clearTimeout(timer);try{await save();}catch(_){}container.removeEventListener('click',click);container.removeEventListener('input',input);container.removeEventListener('change',change);};
}

function csvRows(text) {
  const lines=String(text||'').split(/\r?\n/).filter((line)=>line.trim());if(!lines.length)return[];
  const parse=(line)=>{const out=[];let value='',quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quote&&line[i+1]==='"'){value+='"';i++;}else quote=!quote;}else if(c===','&&!quote){out.push(value);value='';}else value+=c;}out.push(value);return out;};
  const headers=parse(lines[0]);return lines.slice(1).map((line)=>{const values=parse(line);return Object.fromEntries(headers.map((h,i)=>[h||`column_${i+1}`,values[i]??'']));});
}
function datasetRows(record){if(!record)return[];if(record.name.toLowerCase().endsWith('.json')){try{const value=JSON.parse(record.text||'[]');return Array.isArray(value)?value:(Array.isArray(value?.data)?value.data:[value]);}catch(_){return[];}}return csvRows(record.text);}

async function mountData(container,{api,options}) {
  let selectedId=options?.recordId||null;
  async function draw(){const all=await Archive.all();const datasets=all.filter((i)=>i.kind==='dataset');if(!selectedId||!datasets.some((i)=>i.id===selectedId))selectedId=datasets[0]?.id||null;const selected=datasets.find((i)=>i.id===selectedId)||null;const rows=datasetRows(selected);const columns=rows.length?[...new Set(rows.flatMap((row)=>Object.keys(row||{})))].slice(0,40):[];const missing=rows.reduce((sum,row)=>sum+columns.filter((col)=>row?.[col]==null||row[col]==='').length,0);container.innerHTML=`<div class="az-app-shell"><div class="az-app-toolbar"><select data-dataset-select aria-label="Dataset">${datasets.length?datasets.map((item)=>`<option value="${escapeHtml(item.id)}" ${item.id===selectedId?'selected':''}>${escapeHtml(item.name)}</option>`).join(''):'<option>No datasets</option>'}</select><span class="az-system-spacer"></span>${selected?'<button class="az-button" type="button" data-data-note>Send summary to Notes</button>':''}</div>${selected?`<div class="az-data-layout"><div class="az-data-summary"><div class="az-stat-card"><span>Rows</span><strong>${rows.length}</strong></div><div class="az-stat-card"><span>Columns</span><strong>${columns.length}</strong></div><div class="az-stat-card"><span>Missing cells</span><strong>${missing}</strong></div><div class="az-stat-card"><span>Source</span><strong style="font-size:13px">${escapeHtml(selected.meta?.source||'Local import')}</strong></div></div><div class="az-table-wrap">${rows.length?`<table class="az-table"><thead><tr>${columns.map((c)=>`<th>${escapeHtml(c)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,200).map((row)=>`<tr>${columns.map((c)=>`<td title="${escapeHtml(row?.[c]??'')}">${escapeHtml(row?.[c]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<div class="az-empty-state"><div><h3>No readable rows</h3><p>The dataset is stored locally, but this preview could not extract a table.</p></div></div>'}</div></div>`:`<div class="az-empty-state"><div><h3>Bring a dataset into the field</h3><p>Import CSV or JSON through Field Archive, then reopen Data Lab. The source file remains local to this browser.</p><button class="az-button az-button-primary" type="button" data-open-archive>Open Field Archive</button></div></div>`}</div>`;}
  const change=async(event)=>{if(event.target.matches('[data-dataset-select]')){selectedId=event.target.value;await draw();}};
  const click=async(event)=>{if(event.target.closest('[data-open-archive]'))api.openApp('archive');if(event.target.closest('[data-data-note]')){const record=await Archive.get(selectedId);const rows=datasetRows(record);const columns=rows.length?[...new Set(rows.flatMap((r)=>Object.keys(r||{})))]:[];const note=await Archive.createNote(`Dataset summary — ${record.meta?.title||record.name}`,`# Dataset summary — ${record.name}\n\nRows: ${rows.length}\nColumns: ${columns.length}\nFields: ${columns.join(', ')}\nSource: ${record.meta?.source||'Local import'}\n\n## Observation\n\n`,{source:record.meta?.source||'',evidence:'documented',tags:['dataset','summary']});api.openApp('notes',{recordId:note.id});}};
  container.addEventListener('change',change);container.addEventListener('click',click);await draw();return()=>{container.removeEventListener('change',change);container.removeEventListener('click',click);};
}

async function mountReader(container,{api,options}) {
  let selectedId=options?.recordId||null;let objectUrl=null;
  async function draw(){if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null;}const all=await Archive.all();const sources=all.filter((i)=>['pdf','markdown','text'].includes(i.kind));if(!selectedId||!sources.some((i)=>i.id===selectedId))selectedId=sources[0]?.id||null;const selected=sources.find((i)=>i.id===selectedId)||null;let body='<div class="az-empty-state"><div><h3>No sources yet</h3><p>Import a PDF, Markdown or text source through Field Archive.</p><button class="az-button az-button-primary" type="button" data-open-archive>Open Field Archive</button></div></div>';if(selected){if(selected.kind==='pdf'&&selected.blob){objectUrl=URL.createObjectURL(selected.blob);body=`<iframe class="az-pdf-frame" src="${objectUrl}" title="${escapeHtml(selected.name)}"></iframe>`;}else body=`<article><h2>${escapeHtml(selected.meta?.title||selected.name)}</h2><div class="az-reading-meta">${escapeHtml(selected.meta?.source||'Local source')} · ${escapeHtml(selected.meta?.place||'Unspecified place')} · ${escapeHtml(selected.meta?.period||'Unspecified period')}</div>${escapeHtml(selected.text||'No text preview available.')}</article>`;}container.innerHTML=`<div class="az-app-shell"><div class="az-app-toolbar"><strong>Source Reader</strong><span class="az-system-spacer"></span>${selected?`<button class="az-button" type="button" data-copy-citation>Copy citation</button><button class="az-button" type="button" data-source-note>Add field note</button>`:''}</div><div class="az-reader-layout"><nav class="az-reader-list" aria-label="Sources">${sources.map((item)=>`<button type="button" class="${item.id===selectedId?'is-active':''}" data-source-id="${escapeHtml(item.id)}"><strong>${escapeHtml(item.meta?.title||item.name)}</strong><br><small style="color:var(--az-text-3)">${escapeHtml(item.meta?.source||item.collection)}</small></button>`).join('')}</nav><main class="az-reading-surface">${body}</main></div></div>`;}
  const click=async(event)=>{const id=event.target.closest('[data-source-id]')?.dataset.sourceId;if(id){selectedId=id;await draw();return;}if(event.target.closest('[data-open-archive]'))api.openApp('archive');if(event.target.closest('[data-copy-citation]')){const record=await Archive.get(selectedId);const text=`${record.meta?.title||record.name} — ${record.meta?.source||'Local source'}${record.meta?.period?` — ${record.meta.period}`:''}`;try{await navigator.clipboard.writeText(text);api.notify('Citation copied',text);}catch(_){api.notify('Clipboard unavailable','Select the source metadata manually.','warning');}}if(event.target.closest('[data-source-note]')){const record=await Archive.get(selectedId);const note=await Archive.createNote(`Source review — ${record.meta?.title||record.name}`,`${TEMPLATES.source.body}\nLinked source: ${record.name}\nSource: ${record.meta?.source||'—'}\n`,{source:record.meta?.source||'',place:record.meta?.place||'',period:record.meta?.period||'',evidence:'documented',tags:['source-review']});api.openApp('notes',{recordId:note.id});}};
  container.addEventListener('click',click);await draw();return()=>{container.removeEventListener('click',click);if(objectUrl)URL.revokeObjectURL(objectUrl);};
}

async function mountViewer(container,{api,options}) {
  let selectedId=options?.recordId||null;let objectUrl=null;
  async function draw(){if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null;}const all=await Archive.all();const images=all.filter((i)=>i.kind==='image');if(!selectedId||!images.some((i)=>i.id===selectedId))selectedId=images[0]?.id||null;const selected=images.find((i)=>i.id===selectedId)||null;let stage='<div class="az-empty-state"><div><h3>No visual records yet</h3><p>Import an image through Field Archive to inspect it with provenance.</p><button class="az-button az-button-primary" type="button" data-open-archive>Open Field Archive</button></div></div>';if(selected?.blob){objectUrl=URL.createObjectURL(selected.blob);stage=`<img src="${objectUrl}" alt="${escapeHtml(selected.meta?.title||selected.name)}">`;}container.innerHTML=`<div class="az-app-shell"><div class="az-app-toolbar"><strong>Artifact Viewer</strong><span class="az-system-spacer"></span><span style="color:var(--az-text-3);font-size:11px">Visual record · local only</span></div><div class="az-viewer"><nav class="az-viewer-list" aria-label="Visual records">${images.map((item)=>`<button class="az-collection-button${item.id===selectedId?' is-active':''}" type="button" data-image-id="${escapeHtml(item.id)}"><span>${escapeHtml(item.meta?.title||item.name)}</span></button>`).join('')}</nav><main class="az-viewer-stage">${stage}</main><aside class="az-inspector">${selected?metadata(selected):'<p>Select a visual record.</p>'}</aside></div></div>`;}
  const click=async(event)=>{const id=event.target.closest('[data-image-id]')?.dataset.imageId;if(id){selectedId=id;await draw();}if(event.target.closest('[data-open-archive]'))api.openApp('archive');};container.addEventListener('click',click);await draw();return()=>{container.removeEventListener('click',click);if(objectUrl)URL.revokeObjectURL(objectUrl);};
}

export async function mount(context) {
  if(context.appId==='archive')return mountArchive(context.container,context);
  if(context.appId==='notes')return mountNotes(context.container,context);
  if(context.appId==='data-lab')return mountData(context.container,context);
  if(context.appId==='source-reader')return mountReader(context.container,context);
  if(context.appId==='artifact-viewer')return mountViewer(context.container,context);
  throw new Error(`Unknown research application: ${context.appId}`);
}
