import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFileSync, copyFileSync, statSync, existsSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { GLTFLoader } from '../frontend/worlds/shared/vendor/GLTFLoader.js';
import * as THREE from '../frontend/worlds/shared/vendor/three.module.js';

const FRONTEND_GLB = 'frontend/labs/fly-world/assets/fly-house.glb';
const CANONICALIZER = 'scripts/fly-world/canonicalize_glb.py';
const HAVE_GLB_FIXTURE = existsSync(FRONTEND_GLB);
const HAVE_BLENDER = Boolean(process.env.BLENDER_BIN) || spawnSync('which', ['blender']).status === 0;
mkdirSync('/tmp/diag', { recursive: true });

function sha256(path) {
  const bytes = readFileSync(path);
  return createHash('sha256').update(bytes).digest('hex');
}

function runCanonicalizer(glbPath) {
  const candidates = ['python3', 'python'];
  let result;
  let lastErr = '';
  for (const python of candidates) {
    result = spawnSync(python, [CANONICALIZER, glbPath], { encoding: 'utf8' });
    if (result.status === 0) return result.stdout.trim();
    lastErr = `${python}: ${result.stderr || result.stdout}`;
  }
  throw new Error(`canonicalizer failed with all candidates; last error: ${lastErr}`);
}

test('canonicalizer is idempotent on the published Fly House GLB', (t) => {
  if (!HAVE_GLB_FIXTURE) return t.skip('production GLB fixture is generated by the Fly pipeline in CI');
  const sourceBytes = readFileSync(FRONTEND_GLB);
  copyFileSync(FRONTEND_GLB, '/tmp/diag/canon-run-1.glb');
  copyFileSync(FRONTEND_GLB, '/tmp/diag/canon-run-2.glb');
  runCanonicalizer('/tmp/diag/canon-run-1.glb');
  runCanonicalizer('/tmp/diag/canon-run-2.glb');
  // Second pass: run canonicalizer on each result and assert no change.
  runCanonicalizer('/tmp/diag/canon-run-1.glb');
  runCanonicalizer('/tmp/diag/canon-run-2.glb');
  const hash1 = sha256('/tmp/diag/canon-run-1.glb');
  const hash2 = sha256('/tmp/diag/canon-run-2.glb');
  assert.equal(hash1, hash2, 'two identical canonicalization runs produce the same SHA-256');
  assert.equal(
    statSync('/tmp/diag/canon-run-1.glb').size,
    statSync('/tmp/diag/canon-run-2.glb').size,
    'two identical canonicalization runs produce the same byte length',
  );
  // Sanity: canonical output is non-empty and starts with GLB magic.
  assert.ok(sourceBytes.length > 1024, 'source GLB is non-trivial');
  const newBytes = readFileSync('/tmp/diag/canon-run-1.glb');
  assert.equal(newBytes.subarray(0, 4).toString('utf8'), 'glTF', 'canonical output is a GLB');
});

test('canonicalizer preserves the GLB runtime contract', (t) => {
  if (!HAVE_GLB_FIXTURE) return t.skip('production GLB fixture is generated by the Fly pipeline in CI');
  const bytes = readFileSync('/tmp/diag/canon-run-1.glb');
  const ab = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  globalThis.self = globalThis;
  const loader = new GLTFLoader();
  loader.register(() => ({ name: 'noop', loadTexture: () => Promise.resolve(null) }));
  let parsed;
  return loader.parseAsync(ab, '').then((gltf) => {
    parsed = gltf;
    gltf.scene.updateMatrixWorld(true);
    let meshCount = 0;
    let triangleCount = 0;
    gltf.scene.traverse((object) => {
      if (!object.isMesh) return;
      meshCount += 1;
      const index = object.geometry.index;
      triangleCount += index ? index.count / 3 : object.geometry.attributes.position.count / 3;
    });
    assert.ok(meshCount > 50, `canonicalized GLB exposes the expected mesh count (${meshCount})`);
    assert.ok(triangleCount > 1000, `canonicalized GLB exposes the expected triangle count (${Math.round(triangleCount)})`);
    // Spot-check at least one of the named GLB nodes survives canonicalization.
    // The exporter flattens the imported asset hierarchy, so we accept any
    // descendant that carries the wood-stove / bench / cabinet vocabulary.
    const names = new Set();
    gltf.scene.traverse((object) => {
      if (typeof object.name === 'string' && object.name) names.add(object.name);
    });
    const expectedPrefixes = ['stove', 'cabinet', 'divan', 'bench', 'kettle', 'carved'];
    const hit = expectedPrefixes.some((needle) =>
      [...names].some((name) => name.toLowerCase().includes(needle)),
    );
    assert.ok(hit, 'canonicalized GLB still exposes a recognizable stove/cabinet/divan node');
  }).catch((err) => {
    throw new Error(`canonicalized GLB fails to load: ${err?.message || err}`);
  });
});

test('two consecutive exact-source no-render exports are byte-identical', (t) => {
  if (!HAVE_GLB_FIXTURE || !HAVE_BLENDER) return t.skip('requires generated GLB fixture and Blender');
  const run = spawnSync('python3', ['scripts/fly-world/run_pipeline.py', '--strict-assets', '--no-render'], {
    encoding: 'utf8',
    timeout: 300000,
  });
  assert.equal(run.status, 0, `first no-render export failed: ${run.stderr || run.stdout}`);
  copyFileSync(FRONTEND_GLB, '/tmp/diag/determinism-1.glb');
  const firstHash = sha256('/tmp/diag/determinism-1.glb');
  const firstSize = statSync('/tmp/diag/determinism-1.glb').size;

  const second = spawnSync('python3', ['scripts/fly-world/run_pipeline.py', '--strict-assets', '--no-render'], {
    encoding: 'utf8',
    timeout: 300000,
  });
  assert.equal(second.status, 0, `second no-render export failed: ${second.stderr || second.stdout}`);
  const secondHash = sha256(FRONTEND_GLB);
  const secondSize = statSync(FRONTEND_GLB).size;
  assert.equal(secondHash, firstHash, 'consecutive no-render exports have identical SHA-256');
  assert.equal(secondSize, firstSize, 'consecutive no-render exports have identical byte size');
});

test('two canonicalizer runs preserve a valid runtime contract', (t) => {
  if (!HAVE_GLB_FIXTURE) return t.skip('production GLB fixture is generated by the Fly pipeline in CI');
  // The published GLB is canonicalized after export.  This test verifies
  // that canonicalization is idempotent and that two canonicalized copies
  // remain runtime-loadable with the same scene inventory.
  const source = FRONTEND_GLB;
  copyFileSync(source, '/tmp/diag/canon-A.glb');
  copyFileSync(source, '/tmp/diag/canon-B.glb');
  runCanonicalizer('/tmp/diag/canon-A.glb');
  runCanonicalizer('/tmp/diag/canon-B.glb');
  // Re-canonicalize each so we also cover the idempotency assertion.
  runCanonicalizer('/tmp/diag/canon-A.glb');
  runCanonicalizer('/tmp/diag/canon-B.glb');

  const loader = new GLTFLoader();
  loader.register(() => ({ name: 'noop', loadTexture: () => Promise.resolve(null) }));
  const files = ['/tmp/diag/canon-A.glb', '/tmp/diag/canon-B.glb'];
  const scenes = [];
  return Promise.all(files.map((path) => {
    const bytes = readFileSync(path);
    const ab = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
    return loader.parseAsync(ab, '').then((gltf) => gltf.scene.updateMatrixWorld(true) || gltf.scene);
  })).then((parsedScenes) => {
    parsedScenes.forEach((scene) => {
      let meshCount = 0; let vertexCount = 0;
      scene.traverse((object) => {
        if (!object.isMesh) return;
        meshCount += 1;
        vertexCount += object.geometry.attributes.position.count;
      });
      scenes.push({ meshCount, vertexCount });
    });
    assert.equal(scenes[0].meshCount, scenes[1].meshCount,
      'two canonicalized exports agree on mesh count');
    assert.equal(scenes[0].vertexCount, scenes[1].vertexCount,
      'two canonicalized exports agree on total vertex count');
    // JSON metadata of two canonicalized outputs must have the same key
    // inventory (sorted keys, same top-level structure).
    const readJson = (path) => {
      const raw = readFileSync(path);
      let pos = 12;
      while (pos < raw.length) {
        const length = raw.readUInt32LE(pos);
        const type = raw.subarray(pos + 4, pos + 8).toString('utf8');
        if (type === 'JSON') {
          return JSON.parse(raw.subarray(pos + 8, pos + 8 + length).toString('utf8'));
        }
        pos += 8 + length;
      }
      throw new Error('JSON chunk not found');
    };
    const jA = readJson('/tmp/diag/canon-A.glb');
    const jB = readJson('/tmp/diag/canon-B.glb');
    const inventoryA = Object.keys(jA).sort().join(',');
    const inventoryB = Object.keys(jB).sort().join(',');
    assert.equal(inventoryA, inventoryB, 'canonicalized GLBs share the same top-level JSON key set');
  });
});
