/** Private Camera implementation. Shared services arrive only as capabilities. */
const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function mountCamera({container,capabilities}){
  const {filesystem,media,notifications,sound}=capabilities;
  container.innerHTML=`<div class="az-app-shell az-camera-shell"><div class="az-camera"><div class="az-camera-privacy"><strong>Local capture</strong><span>Camera access is requested first. Microphone access is requested separately and is optional; audio is never recorded or uploaded.</span></div><div class="az-camera-stage"><video class="az-camera-video" data-cam-video autoplay playsinline muted></video><canvas class="az-camera-canvas" data-cam-canvas hidden></canvas><div class="az-camera-off" data-cam-off><h3>Camera is off</h3><p>Press Start camera to open the browser permission prompt. Captured photos stay in Workspace · Pictures on this browser.</p><button class="az-button" type="button" data-cam-start>Start camera</button></div></div><div class="az-camera-actions"><button class="az-button az-hr-primary" type="button" data-cam-shot disabled>Capture photo</button><label class="az-camera-toggle"><input type="checkbox" data-cam-mirror checked> Mirror preview</label><span class="az-system-spacer"></span><span class="az-camera-status" data-cam-status role="status" aria-live="polite"></span></div><div class="az-camera-gallery" data-cam-gallery aria-label="Recent photos"></div></div></div>`;
  const video=container.querySelector('[data-cam-video]'),canvas=container.querySelector('[data-cam-canvas]'),offPanel=container.querySelector('[data-cam-off]'),statusEl=container.querySelector('[data-cam-status]'),gallery=container.querySelector('[data-cam-gallery]'),shotBtn=container.querySelector('[data-cam-shot]'),mirrorToggle=container.querySelector('[data-cam-mirror]'),startBtn=container.querySelector('[data-cam-start]');
  let stream=null,starting=false,microphoneActive=false;
  function revokeGalleryUrls(){gallery.querySelectorAll('img[data-photo-src]').forEach((img)=>{if(img.src.startsWith('blob:'))URL.revokeObjectURL(img.src);});}
  async function refreshGallery(){revokeGalleryUrls();const items=await filesystem.childrenOf(filesystem.picturesId),photos=items.filter((node)=>node.kind==='file'&&(node.mime||'').startsWith('image/')).slice(-12).reverse();gallery.innerHTML=photos.length?photos.map((node)=>`<figure class="az-camera-thumb"><img src="#" alt="${esc(node.name)}" data-photo-src="${esc(node.id)}"><figcaption>${esc(node.name)}<button class="az-button" type="button" data-photo-download="${esc(node.id)}">Download</button></figcaption></figure>`).join(''):'<p class="az-camera-empty">Photos you capture appear here (stored in Workspace · Pictures).</p>';for(const node of photos){const blob=await filesystem.readFileBlob(node.id),img=gallery.querySelector(`[data-photo-src="${node.id}"]`);if(blob&&img)img.src=URL.createObjectURL(blob);}}
  function syncVideoReady(){if(!stream)return;const ready=Boolean(video.videoWidth&&video.videoHeight&&video.readyState>=1);shotBtn.disabled=!ready;statusEl.textContent=ready?(microphoneActive?'Camera active · microphone allowed':'Camera active · microphone optional'):'Camera connected, waiting for video…';}
  for(const event of ['loadedmetadata','canplay','playing','resize'])video.addEventListener(event,syncVideoReady);
  async function attachCamera(nextStream){stream=nextStream;microphoneActive=false;video.srcObject=stream;offPanel.hidden=true;shotBtn.disabled=true;statusEl.textContent='Camera connected, waiting for video…';await video.play().catch(()=>{});syncVideoReady();}
  async function requestOptionalMicrophone(cameraStream){statusEl.textContent='Camera active · requesting optional microphone permission…';try{const micStream=await media.getUserMedia({video:false,audio:true});if(stream!==cameraStream){micStream.getTracks().forEach((track)=>track.stop());return false;}const tracks=micStream.getAudioTracks();for(const track of tracks)cameraStream.addTrack(track);microphoneActive=tracks.length>0;syncVideoReady();return microphoneActive;}catch(error){microphoneActive=false;statusEl.textContent=error?.name==='NotAllowedError'?'Camera active · microphone permission was not granted':'Camera active · microphone unavailable';return false;}}
  async function start(){if(starting||stream)return;sound.play('click');if(!media.isAvailable()){statusEl.textContent=globalThis.isSecureContext===false?'Camera access requires HTTPS or localhost.':'This browser does not support camera capture.';return;}starting=true;startBtn.disabled=true;statusEl.textContent='Requesting camera permission…';try{const cameraStream=await media.getUserMedia({video:{facingMode:'user'},audio:false});await attachCamera(cameraStream);const mic=await requestOptionalMicrophone(cameraStream);notifications.notify('Camera',mic?'Camera and microphone connected. Photos stay on this device; microphone audio is not recorded.':'Camera connected. Microphone is optional and photos still work normally.','system');}catch(error){stream?.getTracks().forEach((track)=>track.stop());stream=null;video.srcObject=null;offPanel.hidden=false;shotBtn.disabled=true;statusEl.textContent=error?.name==='NotAllowedError'?'Camera permission is blocked — allow camera access for this site in the browser, then press Start camera again.':error?.name==='NotReadableError'?'Camera is busy or unavailable to this browser.':'Camera unavailable. Check the device and browser camera settings.';sound.play('error');}finally{starting=false;startBtn.disabled=false;}}
  function stop(){stream?.getTracks().forEach((track)=>track.stop());stream=null;video.srcObject=null;microphoneActive=false;offPanel.hidden=false;shotBtn.disabled=true;statusEl.textContent='';}
  async function capture(){if(!stream)return;const w=video.videoWidth,h=video.videoHeight;if(!w||!h){statusEl.textContent='Video is not ready yet. Try again in a moment.';return;}canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.save();if(mirrorToggle.checked){ctx.translate(w,0);ctx.scale(-1,1);}ctx.drawImage(video,0,0);ctx.restore();const blob=await new Promise((resolve)=>canvas.toBlob(resolve,'image/jpeg',.92));if(!blob)return;const stamp=new Date().toISOString().replace(/[:.]/g,'-').slice(0,19);await filesystem.createFile({name:`photo-${stamp}.jpg`,parent:filesystem.picturesId,blob,mime:'image/jpeg'});sound.play('camera');statusEl.textContent='Photo saved to Workspace · Pictures';await refreshGallery();}
  async function download(id){const blob=await filesystem.readFileBlob(id);if(!blob)return;const node=await filesystem.getNode(id),url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=node?.name||'aizanoi-photo.jpg';link.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
  async function handleAction(event){if(event.target.closest('[data-cam-start]'))return start();if(event.target.closest('[data-cam-shot]'))return capture();const id=event.target.closest('[data-photo-download]')?.dataset.photoDownload;if(id)return download(id);}
  const handleClick=(event)=>handleAction(event).catch((error)=>notifications.notify('Camera',error.message,'error'));function handleMirrorChange(){video.dataset.mirrored=mirrorToggle.checked?'true':'false';}function handlePageHide(){stop();}
  container.addEventListener('click',handleClick);mirrorToggle.addEventListener('change',handleMirrorChange);window.addEventListener('pagehide',handlePageHide,{once:true});handleMirrorChange();await refreshGallery();
  return{cleanup(){stop();revokeGalleryUrls();container.removeEventListener('click',handleClick);mirrorToggle.removeEventListener('change',handleMirrorChange);window.removeEventListener('pagehide',handlePageHide);for(const event of ['loadedmetadata','canplay','playing','resize'])video.removeEventListener(event,syncVideoReady);}};
}
