"""Focused US Universe Builder for Aizanoi Markets.

Unions S&P 500, Nasdaq-100, NYSE U.S. 100, DJIA, and Aizanoi Extra into a
canonical, deduplicated, multi-membership focused equity universe (~500–700 securities).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

# Canonical core constituents of Dow Jones Industrial Average (30)
DJIA_TICKERS = {
    "AAPL", "AMGN", "AMZN", "AXP", "BA", "CAT", "CRM", "CSCO", "CVX", "DIS", "GS",
    "HD", "HON", "IBM", "JNJ", "JPM", "KO", "MCD", "MMM", "MRK",
    "MSFT", "NKE", "NVDA", "PG", "SHW", "TRV", "UNH", "V", "VZ", "WMT"
}

# Canonical constituents of Nasdaq-100 (~100)
NASDAQ100_TICKERS = {
    "AAPL", "ABNB", "ADBE", "ADI", "ADP", "ADSK", "AEP", "AMAT", "AMD", "AMGN",
    "AMZN", "APP", "ARM", "ASML", "AVGO", "AXON", "BIIB", "BKNG", "BKR",
    "CCEP", "CDNS", "CDW", "CEG", "CHTR", "CMCSA", "COST", "CPRT", "CRWD", "CSCO",
    "CSX", "CTAS", "CTSH", "DASH", "DDOG", "DLTR", "DXCM", "EA", "EXC", "FANG",
    "FAST", "FTNT", "GEHC", "GFS", "GILD", "GOOG", "GOOGL", "HON", "IDXX", "INTC",
    "INTU", "ISRG", "KDP", "KHC", "KLAC", "LIN", "LRCX", "LULU", "MAR", "MCHP",
    "MCO", "MDLZ", "MELI", "META", "MNST", "MRNA", "MRVL", "MSFT", "MSTR", "MU",
    "NFLX", "NVDA", "NXPI", "ODFL", "ON", "ORLY", "PANW", "PAYX", "PCAR", "PDD",
    "PEP", "PLTR", "PYPL", "QCOM", "REGN", "ROST", "SBUX", "SNPS", "TEAM", "TMUS",
    "TSLA", "TTD", "TXN", "VRSK", "VRTX", "WBD", "WDAY", "XEL", "ZS"
}

# Canonical top ~100 NYSE U.S. 100 blue chips
NYSE_US100_TICKERS = {
    "ABBV", "ABT", "ACN", "AIG", "ALL", "AMH", "AMP", "AON", "APD", "APH",
    "AXP", "BA", "BAC", "BDX", "BK", "BLK", "BMY", "BSX", "C", "CAT",
    "CB", "CI", "CL", "CME", "COF", "COP", "CRM", "CVS", "CVX", "D",
    "DE", "DHR", "DIS", "DUK", "ECL", "ELV", "EMR", "EOG", "ETN", "FCX",
    "FDX", "FMC", "GD", "GE", "GM", "GS", "HCA", "HD", "HLT",
    "HUM", "IBM", "ICE", "ITW", "JNJ", "JPM", "KO", "KR", "LIN", "LLY",
    "LMT", "LOW", "MA", "MCD", "MCK", "MDT", "MET", "MMC", "MMM", "MO",
    "MRK", "MS", "NEE", "NEM", "NKE", "NOC", "ORCL", "PFE", "PG", "PGR",
    "PH", "PLD", "PM", "PNC", "PRU", "RTX", "SCHW", "SHW", "SLB", "SO",
    "SPG", "SPGI", "SYK", "T", "TJX", "TMO", "TRV", "UNH", "UNP", "UPS",
    "USB", "V", "VZ", "WFC", "WMB", "WMT", "XOM"
}

# Major S&P 500 constituents covering all 11 GICS sectors
SP500_CORE_TICKERS = {
    "A", "AAL", "AAPL", "ABBV", "ABNB", "ABT", "ACGL", "ACN", "ADBE", "ADI",
    "ADM", "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG", "AIZ", "AJG",
    "AKAM", "ALB", "ALGN", "ALL", "ALLE", "AMAT", "AMCR", "AMD", "AME", "AMGN",
    "AMP", "AMT", "AMZN", "ANET", "AON", "AOS", "APA", "APD", "APH",
    "APTV", "ARE", "ATO", "AVB", "AVGO", "AVY", "AWK", "AXON", "AXP", "AZO",
    "BA", "BAC", "BALL", "BAX", "BBWI", "BBY", "BDX", "BEN", "BF.B", "BG",
    "BIIB", "BK", "BKNG", "BKR", "BLDR", "BLK", "BMY", "BR", "BRK.B", "BRO",
    "BSX", "BWA", "BX", "BXP", "C", "CAG", "CAH", "CARR", "CAT", "CB",
    "CBOE", "CBRE", "CCI", "CCL", "CDNS", "CDW", "CE", "CEG", "CF", "CFG",
    "CHD", "CHRW", "CHTR", "CI", "CINF", "CL", "CLX", "CMA", "CMCSA", "CME",
    "CMG", "CMI", "CMS", "CNC", "CNP", "COF", "COO", "COP", "COR", "COST",
    "CPAY", "CPB", "CPRT", "CPT", "CRL", "CRM", "CRWD", "CSCO", "CSGP", "CSX",
    "CTAS", "CTLT", "CTRA", "CTSH", "CTVA", "CVS", "CVX", "CZR", "D", "DAL",
    "DAY", "DD", "DE", "DECK", "DELL", "DG", "DGX", "DHI", "DHR",
    "DIS", "DLR", "DLTR", "DOC", "DOV", "DOW", "DPZ", "DRI", "DTE", "DUK",
    "DVA", "DVN", "DXCM", "EA", "EBAY", "ECL", "ED", "EFX", "EG", "EIX",
    "EL", "ELV", "EMN", "EMR", "ENPH", "EOG", "EPAM", "EQIX", "EQR", "EQT",
    "ERIE", "ES", "ESS", "ETN", "ETR", "EVRG", "EW", "EXC", "EXPD", "EXPE",
    "EXR", "F", "FANG", "FAST", "FCX", "FDS", "FDX", "FE", "FFIV", "FI",
    "FICO", "FIS", "FITB", "FMC", "FOX", "FOXA", "FRT", "FSLR", "FTNT",
    "FTV", "GD", "GDDY", "GE", "GEHC", "GEN", "GEV", "GILD", "GIS", "GL",
    "GLW", "GM", "GNRC", "GOOG", "GOOGL", "GPC", "GPN", "GRMN", "GS", "GWW",
    "HAL", "HAS", "HBAN", "HCA", "HD", "HIG", "HII", "HLT", "HOLX",
    "HON", "HPE", "HPQ", "HRL", "HSIC", "HST", "HSY", "HUBB", "HUM", "HWM",
    "IBM", "ICE", "IDXX", "IEX", "IFF", "INCY", "INTC", "INTU", "INVH", "IP",
    "IPG", "IQV", "IR", "IRM", "ISRG", "IT", "ITW", "IVZ", "J", "JBHT",
    "JBL", "JCI", "JKHY", "JNJ", "JPM", "KDP", "KEY", "KEYS",
    "KHC", "KIM", "KLAC", "KMB", "KMI", "KMX", "KO", "KR", "KVUE", "L",
    "LDOS", "LEN", "LH", "LHX", "LIN", "LKQ", "LLY", "LMT", "LNT", "LOW",
    "LRCX", "LULU", "LUV", "LVS", "LW", "LYB", "LYV", "MA", "MAA", "MAR",
    "MAS", "MCD", "MCHP", "MCK", "MCO", "MDLZ", "MDT", "MET", "META", "MGM",
    "MHK", "MKC", "MKTX", "MLM", "MMC", "MMM", "MNST", "MO", "MOH", "MOS",
    "MPC", "MPWR", "MRK", "MRNA", "MS", "MSCI", "MSFT", "MSI", "MTB", "MTCH",
    "MTD", "MU", "NCLH", "NDAQ", "NDSN", "NEE", "NEM", "NFLX", "NI", "NKE",
    "NOC", "NOW", "NRG", "NSC", "NTAP", "NTRS", "NUE", "NVDA", "NVR", "NWS",
    "NWSA", "NXPI", "O", "ODFL", "OKE", "OMC", "ON", "ORCL", "ORLY", "OTIS",
    "OXY", "PANW", "PAYC", "PAYX", "PCAR", "PCG", "PEG", "PEP", "PFE",
    "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PLD", "PLTR", "PM", "PNC",
    "PNR", "PNW", "PODD", "POOL", "PPG", "PPL", "PRU", "PSA", "PSX", "PTC",
    "PWR", "PYPL", "QCOM", "QRVO", "RCL", "REG", "REGN", "RF", "RHI", "RJF",
    "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RSG", "RTX", "RVTY", "SBAC",
    "SBUX", "SCHW", "SHW", "SJM", "SLB", "SMCI", "SNA", "SNPS", "SO", "SPG",
    "SPGI", "SRE", "STE", "STLD", "STT", "STX", "STZ", "SWK", "SWKS", "SYF",
    "SYK", "SYY", "T", "TAP", "TDG", "TDY", "TECH", "TEL", "TER", "TFC",
    "TFX", "TGT", "TJX", "TMO", "TMUS", "TPR", "TRGP", "TRMB", "TROW", "TRV",
    "TSCO", "TSLA", "TSN", "TT", "TTWO", "TXN", "TXT", "TYL", "UAL", "UBER",
    "UDR", "UHS", "ULTA", "UNH", "UNP", "UPS", "URI", "USB", "V", "VICI",
    "VLO", "VLTO", "VMC", "VNO", "VRSK", "VRSN", "VRTX", "VST", "VTR", "VTRS",
    "VZ", "WAB", "WAT", "WBD", "WDC", "WEC", "WELL", "WFC", "WM",
    "WMB", "WMT", "WRB", "WST", "WTW", "WY", "WYNN", "XEL", "XOM", "XYL",
    "YUM", "ZBH", "ZBRA", "ZTS"
}

NAME_OVERRIDES: dict[str, tuple[str, str]] = {
    # Verified via Nasdaq Trader symbol directory + curated manual review (2026-09-10).
    # Real company names only; no fabricated "TICKER Inc." placeholders.
    "A": ("Agilent Technologies, Inc. Common Stock", "NYSE"),
    "AAL": ("American Airlines Group, Inc. - Common Stock", "NASDAQ"),
    "AAPL": ("Apple Inc. - Common Stock", "NASDAQ"),
    "ABBV": ("AbbVie Inc. Common Stock", "NYSE"),
    "ABNB": ("Airbnb, Inc. - Class A Common Stock", "NASDAQ"),
    "ABT": ("Abbott Laboratories Common Stock", "NYSE"),
    "ACGL": ("Arch Capital Group Ltd. - Common Stock", "NASDAQ"),
    "ACN": ("Accenture plc Class A Ordinary Shares (Ireland)", "NYSE"),
    "ADBE": ("Adobe Inc. - Common Stock", "NASDAQ"),
    "ADI": ("Analog Devices, Inc. - Common Stock", "NASDAQ"),
    "ADM": ("Archer-Daniels-Midland Company Common Stock", "NYSE"),
    "ADP": ("Automatic Data Processing, Inc. - Common Stock", "NASDAQ"),
    "ADSK": ("Autodesk, Inc. - Common Stock", "NASDAQ"),
    "AEE": ("Ameren Corporation Common Stock", "NYSE"),
    "AEP": ("American Electric Power Company, Inc. - Common Stock", "NASDAQ"),
    "AES": ("The AES Corporation Common Stock", "NYSE"),
    "AFL": ("AFLAC Incorporated Common Stock", "NYSE"),
    "AIG": ("American International Group, Inc. New Common Stock", "NYSE"),
    "AIZ": ("Assurant, Inc. Common Stock", "NYSE"),
    "AJG": ("Arthur J. Gallagher & Co. Common Stock", "NYSE"),
    "AKAM": ("Akamai Technologies, Inc. - Common Stock", "NASDAQ"),
    "ALB": ("Albemarle Corporation Common Stock", "NYSE"),
    "ALGN": ("Align Technology, Inc. - Common Stock", "NASDAQ"),
    "ALL": ("Allstate Corporation (The) Common Stock", "NYSE"),
    "ALLE": ("Allegion plc Ordinary Shares", "NYSE"),
    "AMAT": ("Applied Materials, Inc. - Common Stock", "NASDAQ"),
    "AMCR": ("Amcor plc Ordinary Shares", "NYSE"),
    "AMD": ("Advanced Micro Devices, Inc. - Common Stock", "NASDAQ"),
    "AME": ("AMETEK, Inc.", "NYSE"),
    "AMGN": ("Amgen Inc. - Common Stock", "NASDAQ"),
    "AMH": ("American Homes 4 Rent Common Shares of Beneficial Interest", "NYSE"),
    "AMP": ("Ameriprise Financial, Inc. Common Stock", "NYSE"),
    "AMT": ("American Tower Corporation (REIT) Common Stock", "NYSE"),
    "AMZN": ("Amazon.com, Inc. - Common Stock", "NASDAQ"),
    "ANET": ("Arista Networks, Inc. Common Stock", "NYSE"),
    "AON": ("Aon plc Class A Ordinary Shares (Ireland)", "NYSE"),
    "AOS": ("A.O. Smith Corporation Common Stock", "NYSE"),
    "APA": ("APA Corporation - Common Stock", "NASDAQ"),
    "APD": ("Air Products and Chemicals, Inc. Common Stock", "NYSE"),
    "APH": ("Amphenol Corporation Common Stock", "NYSE"),
    "APP": ("Applovin Corporation - Class A Common Stock", "NASDAQ"),
    "APTV": ("Aptiv PLC Ordinary Shares", "NYSE"),
    "ARE": ("Alexandria Real Estate Equities, Inc. Common Stock", "NYSE"),
    "ARM": ("Arm Holdings plc - American Depositary Shares", "NASDAQ"),
    "ASML": ("ASML Holding N.V. - New York Registry Shares", "NASDAQ"),
    "ASTS": ("AST SpaceMobile, Inc. - Class A Common Stock", "NASDAQ"),
    "ATO": ("Atmos Energy Corporation Common Stock", "NYSE"),
    "AVB": ("AvalonBay Communities, Inc.", "NYSE"),
    "AVGO": ("Broadcom Inc. - Common Stock", "NASDAQ"),
    "AVY": ("Avery Dennison Corporation Common Stock", "NYSE"),
    "AWK": ("American Water Works Company, Inc. Common Stock", "NYSE"),
    "AXON": ("Axon Enterprise, Inc. - Common Stock", "NASDAQ"),
    "AXP": ("American Express Company Common Stock", "NYSE"),
    "AZO": ("AutoZone, Inc. Common Stock", "NYSE"),
    "BA": ("Boeing Company (The) Common Stock", "NYSE"),
    "BAC": ("Bank of America Corporation Common Stock", "NYSE"),
    "BALL": ("Ball Corporation Common Stock", "NYSE"),
    "BAX": ("Baxter International Inc. Common Stock", "NYSE"),
    "BBWI": ("Bath & Body Works, Inc.", "NYSE"),
    "BBY": ("Best Buy Co., Inc. Common Stock", "NYSE"),
    "BDX": ("Becton, Dickinson and Company Common Stock", "NYSE"),
    "BEN": ("Franklin Templeton, Inc. Common Stock", "NYSE"),
    "BF.B": ("Brown Forman Inc Class B Common Stock", "NYSE"),
    "BG": ("Bunge Limited Common Shares", "NYSE"),
    "BIIB": ("Biogen Inc. - Common Stock", "NASDAQ"),
    "BK": ("The Bank of New York Mellon Corporation", "NYSE"),
    "BKNG": ("Booking Holdings Inc. - Common Stock", "NASDAQ"),
    "BKR": ("Baker Hughes Company - Common Stock", "NASDAQ"),
    "BLDR": ("Builders FirstSource, Inc. Common Stock", "NYSE"),
    "BLK": ("BlackRock, Inc. Common Stock", "NYSE"),
    "BMY": ("Bristol-Myers Squibb Company Common Stock", "NYSE"),
    "BR": ("Broadridge Financial Solutions, Inc. Common Stock", "NYSE"),
    "BRK.B": ("Berkshire Hathaway Inc. New Common Stock", "NYSE"),
    "BRO": ("Brown & Brown, Inc. Common Stock", "NYSE"),
    "BSX": ("Boston Scientific Corporation Common Stock", "NYSE"),
    "BWA": ("BorgWarner Inc. Common Stock", "NYSE"),
    "BX": ("Blackstone Inc. Common Stock", "NYSE"),
    "BXP": ("BXP, Inc. Common Stock", "NYSE"),
    "C": ("Citigroup, Inc. Common Stock", "NYSE"),
    "CAG": ("ConAgra Brands, Inc. Common Stock", "NYSE"),
    "CAH": ("Cardinal Health, Inc. Common Stock", "NYSE"),
    "CARR": ("Carrier Global Corporation Common Stock", "NYSE"),
    "CAT": ("Caterpillar, Inc. Common Stock", "NYSE"),
    "CB": ("Chubb Limited  Common Stock", "NYSE"),
    "CBOE": ("Cboe Global Markets, Inc. Common Stock", "CBOE BZX"),
    "CBRE": ("CBRE Group Inc Common Stock Class A", "NYSE"),
    "CCEP": ("Coca-Cola Europacific Partners plc - Ordinary Shares", "NASDAQ"),
    "CCI": ("Crown Castle Inc. Common Stock", "NYSE"),
    "CCL": ("Carnival Corporation Ltd. Common Shares", "NYSE"),
    "CDNS": ("Cadence Design Systems, Inc. - Common Stock", "NASDAQ"),
    "CDW": ("CDW Corporation - Common Stock", "NASDAQ"),
    "CE": ("Celanese Corporation Common Stock", "NYSE"),
    "CEG": ("Constellation Energy Corporation - Common Stock When-Issued", "NASDAQ"),
    "CF": ("CF Industries Holdings, Inc. Common Stock", "NYSE"),
    "CFG": ("Citizens Financial Group, Inc. Common Stock", "NYSE"),
    "CHD": ("Church & Dwight Company, Inc. Common Stock", "NYSE"),
    "CHRW": ("C.H. Robinson Worldwide, Inc. - Common Stock", "NASDAQ"),
    "CHTR": ("Charter Communications, Inc. - Class A Common Stock", "NASDAQ"),
    "CI": ("The Cigna Group Common Stock", "NYSE"),
    "CINF": ("Cincinnati Financial Corporation - Common Stock", "NASDAQ"),
    "CL": ("Colgate-Palmolive Company Common Stock", "NYSE"),
    "CLX": ("Clorox Company (The) Common Stock", "NYSE"),
    "CMA": ("Comerica Incorporated", "NYSE"),
    "CMCSA": ("Comcast Corporation - Class A Common Stock", "NASDAQ"),
    "CME": ("CME Group Inc. - Class A Common Stock", "NASDAQ"),
    "CMG": ("Chipotle Mexican Grill, Inc. Common Stock", "NYSE"),
    "CMI": ("Cummins Inc. Common Stock", "NYSE"),
    "CMS": ("CMS Energy Corporation Common Stock", "NYSE"),
    "CNC": ("Centene Corporation Common Stock", "NYSE"),
    "CNP": ("CenterPoint Energy, Inc (Holding Co) Common Stock", "NYSE"),
    "COF": ("Capital One Financial Corporation Common Stock", "NYSE"),
    "COIN": ("Coinbase Global, Inc. - Class A Common Stock", "NASDAQ"),
    "COO": ("The Cooper Companies, Inc.  - Common Stock", "NASDAQ"),
    "COP": ("ConocoPhillips Common Stock", "NYSE"),
    "COR": ("Cencora, Inc. Common Stock", "NYSE"),
    "COST": ("Costco Wholesale Corporation - Common Stock", "NASDAQ"),
    "CPAY": ("Corpay, Inc. Common Stock", "NYSE"),
    "CPB": ("The Campbell's Company - Common Stock", "NASDAQ"),
    "CPRT": ("Copart, Inc. - Common Stock", "NASDAQ"),
    "CPT": ("Camden Property Trust Common Stock", "NYSE"),
    "CRL": ("Charles River Laboratories International, Inc. Common Stock", "NYSE"),
    "CRM": ("Salesforce, Inc. Common Stock", "NYSE"),
    "CRWD": ("CrowdStrike Holdings, Inc. - Class A Common Stock", "NASDAQ"),
    "CSCO": ("Cisco Systems, Inc. - Common Stock", "NASDAQ"),
    "CSGP": ("CoStar Group, Inc. - Common Stock", "NASDAQ"),
    "CSX": ("CSX Corporation - Common Stock", "NASDAQ"),
    "CTAS": ("Cintas Corporation - Common Stock", "NASDAQ"),
    "CTLT": ("Catalent, Inc.", "NYSE"),
    "CTRA": ("Coterra Energy Inc.", "NYSE"),
    "CTSH": ("Cognizant Technology Solutions Corporation - Class A Common Stock", "NASDAQ"),
    "CTVA": ("Corteva, Inc. Common Stock", "NYSE"),
    "CVS": ("CVS Health Corporation Common Stock", "NYSE"),
    "CVX": ("Chevron Corporation Common Stock", "NYSE"),
    "CZR": ("Caesars Entertainment, Inc. - Common Stock", "NASDAQ"),
    "D": ("Dominion Energy, Inc. Common Stock", "NYSE"),
    "DAL": ("Delta Air Lines, Inc. Common Stock", "NYSE"),
    "DASH": ("DoorDash, Inc. - Common Stock", "NASDAQ"),
    "DAY": ("Dayforce, Inc.", "NYSE"),
    "DD": ("DuPont de Nemours, Inc. Common Stock", "NYSE"),
    "DDOG": ("Datadog, Inc. - Class A Common Stock", "NASDAQ"),
    "DE": ("Deere & Company Common Stock", "NYSE"),
    "DECK": ("Deckers Outdoor Corporation Common Stock", "NYSE"),
    "DELL": ("Dell Technologies Inc. Class C Common Stock", "NYSE"),
    "DG": ("Dollar General Corporation Common Stock", "NYSE"),
    "DGX": ("Quest Diagnostics Incorporated Common Stock", "NYSE"),
    "DHI": ("D.R. Horton, Inc. Common Stock", "NYSE"),
    "DHR": ("Danaher Corporation Common Stock", "NYSE"),
    "DIS": ("Walt Disney Company (The) Common Stock", "NYSE"),
    "DLR": ("Digital Realty Trust, Inc. Common Stock", "NYSE"),
    "DLTR": ("Dollar Tree, Inc. - Common Stock", "NASDAQ"),
    "DOC": ("Healthpeak Properties, Inc. Common Stock", "NYSE"),
    "DOV": ("Dover Corporation Common Stock", "NYSE"),
    "DOW": ("Dow Inc. Common Stock", "NYSE"),
    "DPZ": ("Domino's Pizza Inc - Common Stock", "NASDAQ"),
    "DRI": ("Darden Restaurants, Inc. Common Stock", "NYSE"),
    "DTE": ("DTE Energy Company Common Stock", "NYSE"),
    "DUK": ("Duke Energy Corporation (Holding Company) Common Stock", "NYSE"),
    "DVA": ("DaVita Inc. Common Stock", "NYSE"),
    "DVN": ("Devon Energy Corporation Common Stock", "NYSE"),
    "DXCM": ("DexCom, Inc. - Common Stock", "NASDAQ"),
    "EA": ("Electronic Arts Inc.", "NASDAQ"),
    "EBAY": ("eBay Inc. - Common Stock", "NASDAQ"),
    "ECL": ("Ecolab Inc. Common Stock", "NYSE"),
    "ED": ("Consolidated Edison, Inc. Common Stock", "NYSE"),
    "EFX": ("Equifax, Inc. Common Stock", "NYSE"),
    "EG": ("Everest Group, Ltd. Common Stock", "NYSE"),
    "EIX": ("Edison International Common Stock", "NYSE"),
    "EL": ("Estee Lauder Companies, Inc. (The) Common Stock", "NYSE"),
    "ELV": ("Elevance Health, Inc. Common Stock", "NYSE"),
    "EMN": ("Eastman Chemical Company Common Stock", "NYSE"),
    "EMR": ("Emerson Electric Company Common Stock", "NYSE"),
    "ENPH": ("Enphase Energy, Inc. - Common Stock", "NASDAQ"),
    "EOG": ("EOG Resources, Inc. Common Stock", "NYSE"),
    "EPAM": ("EPAM Systems, Inc. Common Stock", "NYSE"),
    "EQIX": ("Equinix, Inc. - Common Stock", "NASDAQ"),
    "EQR": ("Equity Residential", "NYSE"),
    "EQT": ("EQT Corporation Common Stock", "NYSE"),
    "ERIE": ("Erie Indemnity Company - Class A Common Stock", "NASDAQ"),
    "ES": ("Eversource Energy (D/B/A) Common Stock", "NYSE"),
    "ESS": ("Essex Property Trust, Inc. Common Stock", "NYSE"),
    "ETN": ("Eaton Corporation, PLC Ordinary Shares", "NYSE"),
    "ETR": ("Entergy Corporation Common Stock", "NYSE"),
    "EVRG": ("Evergy, Inc. - Common Stock", "NASDAQ"),
    "EW": ("Edwards Lifesciences Corporation Common Stock", "NYSE"),
    "EXC": ("Exelon Corporation - Common Stock", "NASDAQ"),
    "EXPD": ("Expeditors International of Washington, Inc. Common Stock", "NYSE"),
    "EXPE": ("Expedia Group, Inc. - Common Stock", "NASDAQ"),
    "EXR": ("Extra Space Storage Inc Common Stock", "NYSE"),
    "F": ("Ford Motor Company Common Stock", "NYSE"),
    "FANG": ("Diamondback Energy, Inc. - Common Stock", "NASDAQ"),
    "FAST": ("Fastenal Company - Common Stock", "NASDAQ"),
    "FCX": ("Freeport-McMoRan, Inc. Common Stock", "NYSE"),
    "FDS": ("FactSet Research Systems Inc. Common Stock", "NYSE"),
    "FDX": ("FedEx Corporation Common Stock", "NYSE"),
    "FE": ("FirstEnergy Corp. Common Stock", "NYSE"),
    "FFIV": ("F5, Inc. - Common Stock", "NASDAQ"),
    "FI": ("Fiserv, Inc.", "NYSE"),
    "FICO": ("Fair Isaac Corporation Common Stock", "NYSE"),
    "FIS": ("Fidelity National Information Services, Inc. Common Stock", "NYSE"),
    "FITB": ("Fifth Third Bancorp Common Stock", "NYSE"),
    "FMC": ("FMC Corporation Common Stock", "NYSE"),
    "FOX": ("Fox Corporation - Class B Common Stock", "NASDAQ"),
    "FOXA": ("Fox Corporation - Class A Common Stock", "NASDAQ"),
    "FRT": ("Federal Realty Investment Trust Common Stock", "NYSE"),
    "FSLR": ("First Solar, Inc. - Common Stock", "NASDAQ"),
    "FTNT": ("Fortinet, Inc. - Common Stock", "NASDAQ"),
    "FTV": ("Fortive Corporation Common Stock", "NYSE"),
    "GD": ("General Dynamics Corporation Common Stock", "NYSE"),
    "GDDY": ("GoDaddy Inc. Class A Common Stock", "NYSE"),
    "GE": ("GE Aerospace Common Stock", "NYSE"),
    "GEHC": ("GE HealthCare Technologies Inc. - Common Stock", "NASDAQ"),
    "GEN": ("Gen Digital Inc. - Common Stock", "NASDAQ"),
    "GEV": ("GE Vernova Inc. Common Stock", "NYSE"),
    "GFS": ("GlobalFoundries Inc. - Ordinary Share", "NASDAQ"),
    "GILD": ("Gilead Sciences, Inc. - Common Stock", "NASDAQ"),
    "GIS": ("General Mills, Inc. Common Stock", "NYSE"),
    "GL": ("Globe Life Inc. Common Stock", "NYSE"),
    "GLW": ("Corning Incorporated Common Stock", "NYSE"),
    "GM": ("General Motors Company Common Stock", "NYSE"),
    "GNRC": ("Generac Holdlings Inc. Common Stock", "NYSE"),
    "GOOG": ("Alphabet Inc. - Class C Capital Stock", "NASDAQ"),
    "GOOGL": ("Alphabet Inc. - Class A Common Stock", "NASDAQ"),
    "GPC": ("Genuine Parts Company Common Stock", "NYSE"),
    "GPN": ("Global Payments Inc. Common Stock", "NYSE"),
    "GRMN": ("Garmin Ltd. Common Stock (Switzerland)", "NYSE"),
    "GS": ("Goldman Sachs Group, Inc. (The) Common Stock", "NYSE"),
    "GWW": ("W.W. Grainger, Inc. Common Stock", "NYSE"),
    "HAL": ("Halliburton Company Common Stock", "NYSE"),
    "HAS": ("Hasbro, Inc. - Common Stock", "NASDAQ"),
    "HBAN": ("Huntington Bancshares Incorporated - Common Stock", "NASDAQ"),
    "HCA": ("HCA Healthcare, Inc. Common Stock", "NYSE"),
    "HD": ("Home Depot, Inc. (The) Common Stock", "NYSE"),
    "HIG": ("The Hartford Insurance Group, Inc. Common Stock", "NYSE"),
    "HII": ("Huntington Ingalls Industries, Inc. Common Stock", "NYSE"),
    "HLT": ("Hilton Worldwide Holdings Inc. Common Stock", "NYSE"),
    "HOLX": ("Hologic, Inc.", "NASDAQ"),
    "HON": ("Honeywell International Inc. - Common Stock", "NASDAQ"),
    "HOOD": ("Robinhood Markets, Inc. - Class A Common Stock", "NASDAQ"),
    "HPE": ("Hewlett Packard Enterprise Company Common Stock", "NYSE"),
    "HPQ": ("HP Inc. Common Stock", "NYSE"),
    "HRL": ("Hormel Foods Corporation Common Stock", "NYSE"),
    "HSIC": ("Henry Schein, Inc. - Common Stock", "NASDAQ"),
    "HST": ("Host Hotels & Resorts, Inc. - Common Stock", "NASDAQ"),
    "HSY": ("The Hershey Company Common Stock", "NYSE"),
    "HUBB": ("Hubbell Inc Common Stock", "NYSE"),
    "HUM": ("Humana Inc. Common Stock", "NYSE"),
    "HWM": ("Howmet Aerospace Inc. Common Stock", "NYSE"),
    "IBM": ("International Business Machines Corporation Common Stock", "NYSE"),
    "ICE": ("Intercontinental Exchange Inc. Common Stock", "NYSE"),
    "IDXX": ("IDEXX Laboratories, Inc. - Common Stock", "NASDAQ"),
    "IEX": ("IDEX Corporation Common Stock", "NYSE"),
    "IFF": ("International Flavors & Fragrances, Inc. Common Stock", "NYSE"),
    "INCY": ("Incyte Corporation - Common Stock", "NASDAQ"),
    "INTC": ("Intel Corporation - Common Stock", "NASDAQ"),
    "INTU": ("Intuit Inc. - Common Stock", "NASDAQ"),
    "INVH": ("Invitation Homes Inc. Common Stock", "NYSE"),
    "IP": ("International Paper Company Common Stock", "NYSE"),
    "IPG": ("The Interpublic Group of Companies, Inc.", "NYSE"),
    "IQV": ("IQVIA Holdings, Inc. Common Stock", "NYSE"),
    "IR": ("Ingersoll Rand Inc. Common Stock", "NYSE"),
    "IRM": ("Iron Mountain Incorporated (Delaware)Common Stock REIT", "NYSE"),
    "ISRG": ("Intuitive Surgical, Inc. - Common Stock", "NASDAQ"),
    "IT": ("Gartner, Inc. Common Stock", "NYSE"),
    "ITW": ("Illinois Tool Works Inc. Common Stock", "NYSE"),
    "IVZ": ("Invesco Ltd Common Stock", "NYSE"),
    "J": ("Jacobs Solutions Inc. Common Stock", "NYSE"),
    "JBHT": ("J.B. Hunt Transport Services, Inc. - Common Stock", "NASDAQ"),
    "JBL": ("Jabil Inc. Common Stock", "NYSE"),
    "JCI": ("Johnson Controls International plc Ordinary Share", "NYSE"),
    "JKHY": ("Jack Henry & Associates, Inc. - Common Stock", "NASDAQ"),
    "JNJ": ("Johnson & Johnson Common Stock", "NYSE"),
    "JPM": ("JP Morgan Chase & Co. Common Stock", "NYSE"),
    "KDP": ("Keurig Dr Pepper Inc. - Common Stock", "NASDAQ"),
    "KEY": ("KeyCorp Common Stock", "NYSE"),
    "KEYS": ("Keysight Technologies Inc. Common Stock", "NYSE"),
    "KHC": ("The Kraft Heinz Company - Common Stock", "NASDAQ"),
    "KIM": ("Kimco Realty Corporation (HC) Common Stock", "NYSE"),
    "KLAC": ("KLA Corporation  - Common Stock", "NASDAQ"),
    "KMB": ("Kimberly-Clark Corporation - Common Stock", "NASDAQ"),
    "KMI": ("Kinder Morgan, Inc. Common Stock", "NYSE"),
    "KMX": ("CarMax Inc", "NYSE"),
    "KO": ("Coca-Cola Company (The) Common Stock", "NYSE"),
    "KR": ("Kroger Company (The) Common Stock", "NYSE"),
    "KVUE": ("Kenvue Inc. Common Stock", "NYSE"),
    "L": ("Loews Corporation Common Stock", "NYSE"),
    "LDOS": ("Leidos Holdings, Inc. Common Stock", "NYSE"),
    "LEN": ("Lennar Corporation Class A Common Stock", "NYSE"),
    "LH": ("Labcorp Holdings Inc. Common Stock", "NYSE"),
    "LHX": ("L3Harris Technologies, Inc. Common Stock", "NYSE"),
    "LIN": ("Linde plc - Ordinary Shares", "NASDAQ"),
    "LKQ": ("LKQ Corporation - Common Stock", "NASDAQ"),
    "LLY": ("Eli Lilly and Company Common Stock", "NYSE"),
    "LMT": ("Lockheed Martin Corporation Common Stock", "NYSE"),
    "LNT": ("Alliant Energy Corporation - Common Stock", "NASDAQ"),
    "LOW": ("Lowe's Companies, Inc. Common Stock", "NYSE"),
    "LRCX": ("Lam Research Corporation - Common Stock", "NASDAQ"),
    "LULU": ("lululemon athletica inc. - Common Stock", "NASDAQ"),
    "LUV": ("Southwest Airlines Company Common Stock", "NYSE"),
    "LVS": ("Las Vegas Sands Corp. Common Stock", "NYSE"),
    "LW": ("Lamb Weston Holdings, Inc. Common Stock", "NYSE"),
    "LYB": ("LyondellBasell Industries NV Ordinary Shares Class A (Netherlands)", "NYSE"),
    "LYV": ("Live Nation Entertainment, Inc. Common Stock", "NYSE"),
    "MA": ("Mastercard Incorporated Common Stock", "NYSE"),
    "MAA": ("Mid-America Apartment Communities, Inc. Common Stock", "NYSE"),
    "MAR": ("Marriott International - Class A Common Stock", "NASDAQ"),
    "MAS": ("Masco Corporation Common Stock", "NYSE"),
    "MCD": ("McDonald's Corporation Common Stock", "NYSE"),
    "MCHP": ("Microchip Technology Incorporated - Common Stock", "NASDAQ"),
    "MCK": ("McKesson Corporation Common Stock", "NYSE"),
    "MCO": ("Moody's Corporation Common Stock", "NYSE"),
    "MDLZ": ("Mondelez International, Inc. - Class A Common Stock", "NASDAQ"),
    "MDT": ("Medtronic plc. Ordinary Shares", "NYSE"),
    "MELI": ("MercadoLibre, Inc. - Common Stock", "NASDAQ"),
    "MET": ("MetLife, Inc. Common Stock", "NYSE"),
    "META": ("Meta Platforms, Inc. - Class A Common Stock", "NASDAQ"),
    "MGM": ("MGM Resorts International Common Stock", "NYSE"),
    "MHK": ("Mohawk Industries, Inc. Common Stock", "NYSE"),
    "MKC": ("McCormick & Company, Incorporated Common Stock", "NYSE"),
    "MKTX": ("MarketAxess Holdings, Inc. - Common Stock", "NASDAQ"),
    "MLM": ("Martin Marietta Materials, Inc. Common Stock", "NYSE"),
    "MMC": ("Marsh & McLennan Companies, Inc.", "NYSE"),
    "MMM": ("3M Company Common Stock", "NYSE"),
    "MNST": ("Monster Beverage Corporation - Common Stock", "NASDAQ"),
    "MO": ("Altria Group, Inc.", "NYSE"),
    "MOH": ("Molina Healthcare Inc Common Stock", "NYSE"),
    "MOS": ("Mosaic Company (The) Common Stock", "NYSE"),
    "MPC": ("Marathon Petroleum Corporation Common Stock", "NYSE"),
    "MPWR": ("Monolithic Power Systems, Inc. - Common Stock", "NASDAQ"),
    "MRK": ("Merck & Company, Inc. Common Stock (new)", "NYSE"),
    "MRNA": ("Moderna, Inc. - Common Stock", "NASDAQ"),
    "MRVL": ("Marvell Technology, Inc. - Common Stock", "NASDAQ"),
    "MS": ("Morgan Stanley Common Stock", "NYSE"),
    "MSCI": ("MSCI Inc. Common Stock", "NYSE"),
    "MSFT": ("Microsoft Corporation - Common Stock", "NASDAQ"),
    "MSI": ("Motorola Solutions, Inc. Common Stock", "NYSE"),
    "MSTR": ("Strategy Inc - Class A Common Stock", "NASDAQ"),
    "MTB": ("M&T Bank Corporation Common Stock", "NYSE"),
    "MTCH": ("Match Group, Inc. - Common Stock", "NASDAQ"),
    "MTD": ("Mettler-Toledo International, Inc. Common Stock", "NYSE"),
    "MU": ("Micron Technology, Inc. - Common Stock", "NASDAQ"),
    "NCLH": ("Norwegian Cruise Line Holdings Ltd. Ordinary Shares", "NYSE"),
    "NDAQ": ("Nasdaq, Inc. - Common Stock", "NASDAQ"),
    "NDSN": ("Nordson Corporation - Common Stock", "NASDAQ"),
    "NEE": ("NextEra Energy, Inc. Common Stock", "NYSE"),
    "NEM": ("Newmont Corporation", "NYSE"),
    "NFLX": ("Netflix, Inc. - Common Stock", "NASDAQ"),
    "NI": ("NiSource Inc Common Stock", "NYSE"),
    "NKE": ("Nike, Inc. Common Stock", "NYSE"),
    "NOC": ("Northrop Grumman Corporation Common Stock", "NYSE"),
    "NOW": ("ServiceNow, Inc. Common Stock", "NYSE"),
    "NRG": ("NRG Energy, Inc. Common Stock", "NYSE"),
    "NSC": ("Norfolk Southern Corporation Common Stock", "NYSE"),
    "NTAP": ("NetApp, Inc. - Common Stock", "NASDAQ"),
    "NTRS": ("Northern Trust Corporation - Common Stock", "NASDAQ"),
    "NUE": ("Nucor Corporation Common Stock", "NYSE"),
    "NVDA": ("NVIDIA Corporation - Common Stock", "NASDAQ"),
    "NVR": ("NVR, Inc. Common Stock", "NYSE"),
    "NWS": ("News Corporation - Class B Common Stock", "NASDAQ"),
    "NWSA": ("News Corporation - Class A Common Stock", "NASDAQ"),
    "NXPI": ("NXP Semiconductors N.V. - Common Stock", "NASDAQ"),
    "O": ("Realty Income Corporation Common Stock", "NYSE"),
    "ODFL": ("Old Dominion Freight Line, Inc. - Common Stock", "NASDAQ"),
    "OKE": ("ONEOK, Inc. Common Stock", "NYSE"),
    "OMC": ("Omnicom Group Inc. Common Stock", "NYSE"),
    "ON": ("ON Semiconductor Corporation - Common Stock", "NASDAQ"),
    "ORCL": ("Oracle Corporation Common Stock", "NYSE"),
    "ORLY": ("O'Reilly Automotive, Inc. - Common Stock", "NASDAQ"),
    "OTIS": ("Otis Worldwide Corporation Common Stock", "NYSE"),
    "OXY": ("Occidental Petroleum Corporation Common Stock", "NYSE"),
    "PANW": ("Palo Alto Networks, Inc. - Common Stock", "NASDAQ"),
    "PAYC": ("Paycom Software, Inc. Common Stock", "NYSE"),
    "PAYX": ("Paychex, Inc. - Common Stock", "NASDAQ"),
    "PCAR": ("PACCAR Inc. - Common Stock", "NASDAQ"),
    "PCG": ("Pacific Gas & Electric Co. Common Stock", "NYSE"),
    "PDD": ("PDD Holdings Inc. - American Depositary Shares", "NASDAQ"),
    "PEG": ("Public Service Enterprise Group Incorporated Common Stock", "NYSE"),
    "PEP": ("PepsiCo, Inc. - Common Stock", "NASDAQ"),
    "PFE": ("Pfizer, Inc. Common Stock", "NYSE"),
    "PFG": ("Principal Financial Group Inc - Common Stock", "NASDAQ"),
    "PG": ("Procter & Gamble Company (The) Common Stock", "NYSE"),
    "PGR": ("Progressive Corporation (The) Common Stock", "NYSE"),
    "PH": ("Parker-Hannifin Corporation Common Stock", "NYSE"),
    "PHM": ("PulteGroup, Inc. Common Stock", "NYSE"),
    "PKG": ("Packaging Corporation of America Common Stock", "NYSE"),
    "PLD": ("Prologis, Inc. Common Stock", "NYSE"),
    "PLTR": ("Palantir Technologies Inc. - Class A Common Stock", "NASDAQ"),
    "PM": ("Philip Morris International Inc Common Stock", "NYSE"),
    "PNC": ("PNC Financial Services Group, Inc. (The) Common Stock", "NYSE"),
    "PNR": ("Pentair plc. Ordinary Share", "NYSE"),
    "PNW": ("Pinnacle West Capital Corporation Common Stock", "NYSE"),
    "PODD": ("Insulet Corporation - Common Stock", "NASDAQ"),
    "POOL": ("Pool Corporation - Common Stock", "NASDAQ"),
    "PPG": ("PPG Industries, Inc. Common Stock", "NYSE"),
    "PPL": ("PPL Corporation Common Stock", "NYSE"),
    "PRU": ("Prudential Financial, Inc. Common Stock", "NYSE"),
    "PSA": ("Public Storage Common Stock", "NYSE"),
    "PSX": ("Phillips 66 Common Stock", "NYSE"),
    "PTC": ("PTC Inc. - Common Stock", "NASDAQ"),
    "PWR": ("Quanta Services, Inc. Common Stock", "NYSE"),
    "PYPL": ("PayPal Holdings, Inc. - Common Stock", "NASDAQ"),
    "QCOM": ("QUALCOMM Incorporated - Common Stock", "NASDAQ"),
    "QRVO": ("Qorvo, Inc. - Common Stock", "NASDAQ"),
    "RCL": ("Royal Caribbean Cruises Ltd. Common Stock", "NYSE"),
    "RDDT": ("Reddit, Inc. Class A Common Stock", "NYSE"),
    "REG": ("Regency Centers Corporation - Common Stock", "NASDAQ"),
    "REGN": ("Regeneron Pharmaceuticals, Inc. - Common Stock", "NASDAQ"),
    "RF": ("Regions Financial Corporation Common Stock", "NYSE"),
    "RHI": ("Robert Half Inc. Common Stock", "NYSE"),
    "RIVN": ("Rivian Automotive, Inc. - Class A Common Stock", "NASDAQ"),
    "RJF": ("Raymond James Financial, Inc. Common Stock", "NYSE"),
    "RL": ("Ralph Lauren Corporation Common Stock", "NYSE"),
    "RMD": ("ResMed Inc. Common Stock", "NYSE"),
    "ROK": ("Rockwell Automation, Inc. Common Stock", "NYSE"),
    "ROL": ("Rollins, Inc. Common Stock", "NYSE"),
    "ROP": ("Roper Technologies, Inc. - Common Stock", "NASDAQ"),
    "ROST": ("Ross Stores, Inc. - Common Stock", "NASDAQ"),
    "RSG": ("Republic Services, Inc. Common Stock", "NYSE"),
    "RTX": ("RTX Corporation Common Stock", "NYSE"),
    "RVTY": ("Revvity, Inc. Common Stock", "NYSE"),
    "SBAC": ("SBA Communications Corporation - Class A Common Stock", "NASDAQ"),
    "SBUX": ("Starbucks Corporation - Common Stock", "NASDAQ"),
    "SCHW": ("Charles Schwab Corporation (The) Common Stock", "NYSE"),
    "SHW": ("Sherwin-Williams Company (The) Common Stock", "NYSE"),
    "SJM": ("The J.M. Smucker Company Common Stock", "NYSE"),
    "SLB": ("SLB Limited Common Shares", "NYSE"),
    "SMCI": ("Super Micro Computer, Inc. - Common Stock", "NASDAQ"),
    "SNA": ("Snap-On Incorporated Common Stock", "NYSE"),
    "SNPS": ("Synopsys, Inc. - Common Stock", "NASDAQ"),
    "SO": ("Southern Company (The) Common Stock", "NYSE"),
    "SOFI": ("SoFi Technologies, Inc.  - Common Stock", "NASDAQ"),
    "SPG": ("Simon Property Group, Inc. Common Stock", "NYSE"),
    "SPGI": ("S&P Global Inc. Common Stock", "NYSE"),
    "SRE": ("DBA Sempra Common Stock", "NYSE"),
    "STE": ("STERIS plc (Ireland) Ordinary Shares", "NYSE"),
    "STLD": ("Steel Dynamics, Inc. - Common Stock", "NASDAQ"),
    "STT": ("State Street Corporation Common Stock", "NYSE"),
    "STX": ("Seagate Technology Holdings PLC - Ordinary Shares (Ireland)", "NASDAQ"),
    "STZ": ("Constellation Brands, Inc. Common Stock", "NYSE"),
    "SWK": ("Stanley Black & Decker, Inc. Common Stock", "NYSE"),
    "SWKS": ("Skyworks Solutions, Inc. - Common Stock", "NASDAQ"),
    "SYF": ("Synchrony Financial Common Stock", "NYSE"),
    "SYK": ("Stryker Corporation Common Stock", "NYSE"),
    "SYY": ("Sysco Corporation Common Stock", "NYSE"),
    "T": ("AT&T Inc.", "NYSE"),
    "TAP": ("Molson Coors Beverage Company Class B Common Stock", "NYSE"),
    "TDG": ("Transdigm Group Incorporated Common Stock", "NYSE"),
    "TDY": ("Teledyne Technologies Incorporated Common Stock", "NYSE"),
    "TEAM": ("Atlassian Corporation  - Class A Common Stock", "NASDAQ"),
    "TECH": ("Bio-Techne Corp - Common Stock", "NASDAQ"),
    "TEL": ("TE Connectivity plc Ordinary Shares", "NYSE"),
    "TER": ("Teradyne, Inc. - Common Stock", "NASDAQ"),
    "TFC": ("Truist Financial Corporation Common Stock", "NYSE"),
    "TFX": ("Teleflex Incorporated Common Stock", "NYSE"),
    "TGT": ("Target Corporation Common Stock", "NYSE"),
    "TJX": ("TJX Companies, Inc. (The) Common Stock", "NYSE"),
    "TMO": ("Thermo Fisher Scientific Inc Common Stock", "NYSE"),
    "TMUS": ("T-Mobile US, Inc. - Common Stock", "NASDAQ"),
    "TPR": ("Tapestry, Inc. Common Stock", "NYSE"),
    "TRGP": ("Targa Resources, Inc. Common Stock", "NYSE"),
    "TRMB": ("Trimble Inc. - Common Stock", "NASDAQ"),
    "TROW": ("T. Rowe Price Group, Inc. - Common Stock", "NASDAQ"),
    "TRV": ("The Travelers Companies, Inc. Common Stock", "NYSE"),
    "TSCO": ("Tractor Supply Company - Common Stock", "NASDAQ"),
    "TSLA": ("Tesla, Inc.  - Common Stock", "NASDAQ"),
    "TSN": ("Tyson Foods, Inc. Common Stock", "NYSE"),
    "TT": ("Trane Technologies plc", "NYSE"),
    "TTD": ("The Trade Desk, Inc. - Class A Common Stock", "NASDAQ"),
    "TTWO": ("Take-Two Interactive Software, Inc. - Common Stock", "NASDAQ"),
    "TXN": ("Texas Instruments Incorporated - Common Stock", "NASDAQ"),
    "TXT": ("Textron Inc. Common Stock", "NYSE"),
    "TYL": ("Tyler Technologies, Inc. Common Stock", "NYSE"),
    "UAL": ("United Airlines Holdings, Inc. - Common Stock", "NASDAQ"),
    "UBER": ("Uber Technologies, Inc. Common Stock", "NYSE"),
    "UDR": ("UDR, Inc. Common Stock", "NYSE"),
    "UHS": ("Universal Health Services, Inc. Common Stock", "NYSE"),
    "ULTA": ("Ulta Beauty, Inc. - Common Stock", "NASDAQ"),
    "UNH": ("UnitedHealth Group Incorporated Common Stock (DE)", "NYSE"),
    "UNP": ("Union Pacific Corporation Common Stock", "NYSE"),
    "UPS": ("United Parcel Service, Inc. Common Stock", "NYSE"),
    "URI": ("United Rentals, Inc. Common Stock", "NYSE"),
    "USB": ("U.S. Bancorp Common Stock", "NYSE"),
    "V": ("Visa Inc.", "NYSE"),
    "VICI": ("VICI Properties Inc. Common Stock", "NYSE"),
    "VLO": ("Valero Energy Corporation Common Stock", "NYSE"),
    "VLTO": ("Veralto Corp Common Stock", "NYSE"),
    "VMC": ("Vulcan Materials Company (Holding Company) Common Stock", "NYSE"),
    "VNO": ("Vornado Realty Trust Common Stock", "NYSE"),
    "VRSK": ("Verisk Analytics, Inc. - Common Stock", "NASDAQ"),
    "VRSN": ("VeriSign, Inc. - Common Stock", "NASDAQ"),
    "VRTX": ("Vertex Pharmaceuticals Incorporated - Common Stock", "NASDAQ"),
    "VST": ("Vistra Corp. Common Stock", "NYSE"),
    "VTR": ("Ventas, Inc. Common Stock", "NYSE"),
    "VTRS": ("Viatris Inc. - Common Stock", "NASDAQ"),
    "VZ": ("Verizon Communications Inc. Common Stock", "NYSE"),
    "WAB": ("Westinghouse Air Brake Technologies Corporation Common Stock", "NYSE"),
    "WAT": ("Waters Corporation Common Stock", "NYSE"),
    "WBD": ("Warner Bros. Discovery, Inc. - Series A Common Stock", "NASDAQ"),
    "WDAY": ("Workday, Inc. - Class A Common Stock", "NASDAQ"),
    "WDC": ("Western Digital Corporation - Common Stock", "NASDAQ"),
    "WEC": ("WEC Energy Group, Inc. Common Stock", "NYSE"),
    "WELL": ("Welltower Inc. Common Stock", "NYSE"),
    "WFC": ("Wells Fargo & Company Common Stock", "NYSE"),
    "WM": ("Waste Management, Inc. Common Stock", "NYSE"),
    "WMB": ("Williams Companies, Inc. (The) Common Stock", "NYSE"),
    "WMT": ("Walmart Inc. - Common Stock", "NASDAQ"),
    "WRB": ("W.R. Berkley Corporation Common Stock", "NYSE"),
    "WST": ("West Pharmaceutical Services, Inc. Common Stock", "NYSE"),
    "WTW": ("Willis Towers Watson Public Limited Company - Ordinary Shares", "NASDAQ"),
    "WY": ("Weyerhaeuser Company Common Stock", "NYSE"),
    "WYNN": ("Wynn Resorts, Limited - Common Stock", "NASDAQ"),
    "XEL": ("Xcel Energy Inc. - Common Stock", "NASDAQ"),
    "XOM": ("ExxonMobil Holdings Corporation Common Stock", "NYSE"),
    "XYL": ("Xylem Inc. Common Stock New", "NYSE"),
    "YUM": ("Yum! Brands, Inc.", "NYSE"),
    "ZBH": ("Zimmer Biomet Holdings, Inc. Common Stock", "NYSE"),
    "ZBRA": ("Zebra Technologies Corporation - Class A Common Stock", "NASDAQ"),
    "ZS": ("Zscaler, Inc. - Common Stock", "NASDAQ"),
    "ZTS": ("Zoetis Inc. Class A Common Stock", "NYSE"),
}


def slugify(symbol: str) -> str:
    return symbol.lower().replace(".", "-")


def build_focused_us_universe(
    extra_path: Path | None = None,
) -> list[dict[str, Any]]:
    """Build union of S&P 500, Nasdaq-100, NYSE U.S. 100, DJIA, and Extra."""
    extra_items: list[dict[str, str]] = []
    if extra_path and extra_path.exists():
        try:
            extra_items = json.loads(extra_path.read_text(encoding="utf-8"))
        except Exception:
            extra_items = []

    extra_map = {item["ticker"]: item for item in extra_items if "ticker" in item}

    all_tickers = sorted(SP500_CORE_TICKERS | NASDAQ100_TICKERS | NYSE_US100_TICKERS | DJIA_TICKERS | set(extra_map.keys()))

    universe: list[dict[str, Any]] = []
    for ticker in all_tickers:
        memberships: list[str] = []
        if ticker in SP500_CORE_TICKERS:
            memberships.append("sp500")
        if ticker in NASDAQ100_TICKERS:
            memberships.append("nasdaq100")
        if ticker in NYSE_US100_TICKERS:
            memberships.append("nyse_us100")
        if ticker in DJIA_TICKERS:
            memberships.append("djia")
        if ticker in extra_map:
            memberships.append("extra")

        override = NAME_OVERRIDES.get(ticker)
        if override:
            name, exchange = override
        elif ticker in extra_map:
            name, exchange = "", ""  # extra values overwrite below
        else:
            raise ValueError(f"No verified name/exchange for ticker {ticker}; refusing to fabricate metadata")
        if ticker in extra_map:
            name = extra_map[ticker].get("name", name)
            exchange = extra_map[ticker].get("exchange", exchange)

        # Fintable consumes the verified ACT symbol verbatim; dot-class shares
        # such as BRK.B/BF.B must never be converted to dash forms.
        provider_symbol = ticker
        universe.append({
            "market": "us",
            "ticker": ticker,
            "name": name,
            "exchange": exchange,
            "slug": slugify(ticker),
            "provider": "fintable",
            "providerSymbol": provider_symbol,
            "memberships": memberships,
        })

    return universe


def validate_universe_transition(
    old_universe: list[dict[str, Any]],
    new_universe: list[dict[str, Any]],
    min_count: int = 400,
    max_count: int = 800,
) -> bool:
    """Reject malformed or suspicious canonical-universe replacements."""
    count = len(new_universe)
    if count < min_count or count > max_count:
        return False
    required = ("market", "ticker", "name", "exchange", "slug", "provider", "providerSymbol", "memberships")
    if any(any(not row.get(field) for field in required) for row in new_universe):
        return False
    for field in ("ticker", "slug", "providerSymbol"):
        values = [row[field] for row in new_universe]
        if len(values) != len(set(values)):
            return False
    if old_universe:
        old_count = len(old_universe)
        if count < old_count * 0.65 or count > old_count * 1.50:
            return False
    return True
