const esc=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const categoryLabel=(value)=>({ai:'AI',technology:'Technology','economy-markets':'Economy / Markets',football:'Football'}[value]||value);
const dateLabel=(value)=>{if(!value)return'';try{return new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'numeric',month:'short',year:'numeric'}).format(new Date(`${value}T00:00:00Z`));}catch(_){return value;}};
const editionItems=(feed,edition,kind='daily')=>edition?(Array.isArray(feed?.items)?feed.items:[]).filter((item)=>String(item.publishedAt||'').slice(0,10)===edition.date&&(kind==='weekly'?item.kind==='weekly':item.kind!=='weekly')):[];
function sourceLinks(item){return (item?.sources||[]).slice(0,3).map((source)=>`<a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">${esc(source.publisher)}</a>`).join('<span aria-hidden="true"> · </span>');}
function bookSpines(editions,{weekly=false}={}){return editions.slice(0,12).map((edition,index)=>`<a class="az-news-spine${weekly?' az-news-spine--weekly':''}${index===0?' is-latest':''}" href="${esc(edition.path)}" aria-label="Open ${weekly?'weekly':'daily'} edition ${esc(edition.date)}"><span>${weekly?esc(edition.week):dateLabel(edition.date)}</span><strong>${weekly?'Weekly':'Daily'}</strong><small>${edition.itemCount} ${edition.itemCount===1?'story':'stories'}</small></a>`).join('');}
function storyRows(items){return items.slice(0,8).map((item,index)=>`<article class="az-news-library-story${index===0?' is-lead':''}"><div><p class="az-kicker">${esc(categoryLabel(item.category))}</p><h4>${esc(item.title)}</h4>${index===0?`<p>${esc(item.summary)}</p>`:''}</div><footer><span>By ${esc(item.author?.name||'Aizanoi News')}</span><span class="az-news-story-sources">${sourceLinks(item)}</span></footer></article>`).join('');}
export function renderNewsFeed(feed){
  const editions=Array.isArray(feed?.editions)?feed.editions:[],weeklyEditions=Array.isArray(feed?.weeklyEditions)?feed.weeklyEditions:[];
  const current=editions[0],weekly=weeklyEditions[0];
  if(!current&&!weekly)return `<div class="az-news-empty"><p class="az-kicker">READING ROOM</p><h3>The shelves are ready</h3><p>The News Desk is preparing original, concise reports with named editors and linked sources.</p><a class="az-button" href="/news/">Visit the News archive</a></div>`;
  const currentItems=editionItems(feed,current),weeklyItems=editionItems(feed,weekly,'weekly');
  const lead=currentItems[0],weeklyLead=weeklyItems[0];
  const weeklyTopics=[...new Set(weeklyItems.map((item)=>categoryLabel(item.category)))].slice(0,4);
  return `<div class="az-news-library">
    <header class="az-news-library-head"><div><p class="az-kicker">AIZANOI READING ROOM</p><h2>News Library</h2><p>Daily volumes, weekly editions and source-linked reporting kept as a browsable record.</p></div><a class="az-button" href="/news/">Open full archive</a></header>
    <section class="az-news-feature-shelf" aria-label="Featured editions">
      ${current?`<article class="az-news-volume az-news-volume--daily"><div class="az-news-volume-edge" aria-hidden="true"></div><div class="az-news-volume-copy"><p class="az-news-volume-label">Current edition · ${esc(dateLabel(current.date))}</p><h3>Aizanoi<br>News</h3><p class="az-news-volume-deck">${lead?esc(lead.title):'The latest source-linked daily edition.'}</p><div class="az-news-volume-meta"><span>${current.itemCount} ${current.itemCount===1?'story':'stories'}</span><span>Daily record</span></div><a class="az-news-volume-open" href="${esc(current.path)}">Read volume <span aria-hidden="true">→</span></a></div></article>`:''}
      ${weekly?`<article class="az-news-volume az-news-volume--weekly"><div class="az-news-weekly-mark">WEEKLY</div><div class="az-news-volume-copy"><p class="az-news-volume-label">Weekly edition · ${esc(weekly.week)} · ${esc(dateLabel(weekly.date))}</p><h3>The Weekly<br>Edition</h3><p class="az-news-volume-deck">${weeklyLead?esc(weeklyLead.title):'The week edited into one considered volume.'}</p>${weeklyTopics.length?`<div class="az-news-weekly-topics">${weeklyTopics.map((topic)=>`<span>${esc(topic)}</span>`).join('')}</div>`:''}<div class="az-news-volume-meta"><span>${weekly.itemCount} ${weekly.itemCount===1?'feature':'features'}</span><span>Weekly review</span></div><a class="az-news-volume-open" href="${esc(weekly.path)}">Open weekly edition <span aria-hidden="true">→</span></a></div></article>`:''}
    </section>
    ${editions.length?`<section class="az-news-shelf"><header><div><p class="az-kicker">DAILY ARCHIVE</p><h3>The daily shelf</h3></div><span>${editions.length} ${editions.length===1?'edition':'editions'} in the catalogue</span></header><div class="az-news-shelf-board">${bookSpines(editions)}</div></section>`:''}
    ${weeklyEditions.length?`<section class="az-news-shelf az-news-shelf--weekly"><header><div><p class="az-kicker">WEEKLY EDITIONS</p><h3>Collected weeklies</h3></div><span>${weeklyEditions.length} weekly ${weeklyEditions.length===1?'volume':'volumes'}</span></header><div class="az-news-shelf-board">${bookSpines(weeklyEditions,{weekly:true})}</div></section>`:''}
    ${current?`<section class="az-news-reading-list"><header><div><p class="az-kicker">ON THE DESK · ${esc(dateLabel(current.date))}</p><h3>Inside the latest edition</h3></div><a href="${esc(current.path)}">Read complete edition</a></header><div class="az-news-library-stories">${storyRows(currentItems)}</div></section>`:''}
  </div>`;
}
export function createNewsApp(){return{async mount(container){const controller=new AbortController();let disposed=false;container.innerHTML='<div class="az-news-app"><div class="az-news-loading"><div><p class="az-kicker">READING ROOM</p><h3>Opening the News Library…</h3><p>Cataloguing daily and weekly editions.</p></div></div></div>';const host=container.querySelector('.az-news-app');try{const response=await fetch('/news/index.json',{cache:'no-cache',signal:controller.signal});if(!response.ok)throw new Error(`News feed returned ${response.status}`);const feed=await response.json();if(!disposed)host.innerHTML=renderNewsFeed(feed);}catch(error){if(error?.name!=='AbortError'&&!disposed)host.innerHTML=`<div class="az-empty-state"><div><h3>News feed unavailable</h3><p>${esc(error.message)}</p><a class="az-button" href="/news/">Open the News archive</a></div></div>`;}return()=>{disposed=true;controller.abort();};}};}
