/* Browser-safe deterministic Stage B core. No backend, shell, secrets or remote execution. */

export const PROVENANCE_LABELS = Object.freeze(['CONNECTOME-DERIVED', 'BIOLOGICALLY CONSTRAINED', 'MODELLED', 'HEURISTIC']);
const REQUIRED_PROVENANCE = ['units', 'calibrated', 'assumptions', 'limitations', 'version', 'sourceReferences'];
export function validateProvenance(value) {
  if (!value || !PROVENANCE_LABELS.includes(value.label)) throw new TypeError('invalid provenance label');
  if (typeof value.source !== 'string' || !value.source) throw new TypeError('provenance source required');
  for (const key of REQUIRED_PROVENANCE) if (value[key] === undefined) throw new TypeError(`provenance ${key} required`);
  if (typeof value.calibrated !== 'boolean' || !Array.isArray(value.assumptions) || !Array.isArray(value.limitations) || !Array.isArray(value.sourceReferences) || !value.version) throw new TypeError('invalid provenance metadata');
  return Object.freeze({ label: value.label, source: value.source, sourceReferences: Object.freeze([...value.sourceReferences]), units: String(value.units), calibrated: value.calibrated, assumptions: Object.freeze([...value.assumptions]), limitations: Object.freeze([...value.limitations]), version: String(value.version) });
}
const MODELLED = Object.freeze({ label: 'MODELLED', source: 'fly-simulation-stage-b', units: 'SI', calibrated: false, assumptions: ['deterministic reduced-order model'], limitations: ['not a biological or calibrated physiology model'], version: 'stage-b-1', sourceReferences: [] });
const n = (v) => Number.isFinite(v) ? v : 0;
export class Vec3 {
  constructor(x=0, y=0, z=0) { this.x=n(x); this.y=n(y); this.z=n(z); }
  clone(){return new Vec3(this.x,this.y,this.z)} add(v){return new Vec3(this.x+v.x,this.y+v.y,this.z+v.z)} sub(v){return new Vec3(this.x-v.x,this.y-v.y,this.z-v.z)} mul(s){return new Vec3(this.x*s,this.y*s,this.z*s)} dot(v){return this.x*v.x+this.y*v.y+this.z*v.z} length(){return Math.hypot(this.x,this.y,this.z)} normalize(){const l=this.length();return l?this.mul(1/l):new Vec3()}
  toJSON(){return [this.x,this.y,this.z]}
}
export class Quat {
  constructor(x=0,y=0,z=0,w=1){const q={x:n(x),y:n(y),z:n(z),w:n(w)};const l=Math.hypot(q.x,q.y,q.z,q.w)||1;this.x=q.x/l;this.y=q.y/l;this.z=q.z/l;this.w=q.w/l}
  clone(){return new Quat(this.x,this.y,this.z,this.w)} toJSON(){return [this.x,this.y,this.z,this.w]}
}
export class BodyState {
  constructor({ position=new Vec3(), velocity=new Vec3(), orientation=new Quat(), angularVelocity=new Vec3(), mass=1, radius=.25, damping=.02, drag=.02 }={}) { this.position=position instanceof Vec3?position:asVec(position);this.velocity=velocity instanceof Vec3?velocity:asVec(velocity);this.orientation=orientation instanceof Quat?orientation:new Quat(orientation?.x??orientation?.[0]??0,orientation?.y??orientation?.[1]??0,orientation?.z??orientation?.[2]??0,orientation?.w??orientation?.[3]??1);this.angularVelocity=angularVelocity instanceof Vec3?angularVelocity:asVec(angularVelocity);this.mass=mass;this.radius=radius;this.damping=damping;this.drag=drag;this.force=new Vec3();this.torque=new Vec3();this.thrust=new Vec3(); }
  applyForce(force){if(!(force instanceof Vec3))throw new TypeError('force must be Vec3');this.force=this.force.add(force)} applyTorque(torque){if(!(torque instanceof Vec3))throw new TypeError('torque must be Vec3');this.torque=this.torque.add(torque)} applyThrust(thrust){if(!(thrust instanceof Vec3))throw new TypeError('thrust must be Vec3');this.thrust=this.thrust.add(thrust)}
  integrate(dt,gravity){const acceleration=gravity.add(this.force.add(this.thrust).mul(1/this.mass));this.velocity=this.velocity.add(acceleration.mul(dt));this.velocity=this.velocity.mul(Math.max(0,1-this.drag*dt));this.velocity=this.velocity.mul(Math.max(0,1-this.damping*dt));this.position=this.position.add(this.velocity.mul(dt));this.angularVelocity=this.angularVelocity.add(this.torque.mul(dt/this.mass)).mul(Math.max(0,1-this.damping*dt));if(this.angularVelocity.length()>0){const w=this.angularVelocity;const q=this.orientation;const h=dt/2;this.orientation=new Quat((w.x*q.w+w.y*q.z-w.z*q.y)*h+q.x,(w.y*q.w+w.z*q.x-w.x*q.z)*h+q.y,(w.z*q.w+w.x*q.y-w.y*q.x)*h+q.z,(-w.x*q.x-w.y*q.y-w.z*q.z)*h+q.w)}this.force=new Vec3();this.torque=new Vec3();this.thrust=new Vec3()}
  toJSON(){return {position:this.position.toJSON(),velocity:this.velocity.toJSON(),orientation:this.orientation.toJSON(),angularVelocity:this.angularVelocity.toJSON(),mass:this.mass,radius:this.radius,damping:this.damping,drag:this.drag}}
}
function asVec(v){return v instanceof Vec3?v:new Vec3(v?.x??v?.[0]??0,v?.y??v?.[1]??0,v?.z??v?.[2]??0)}
export class AuthoredSurfaceAdapter {
  constructor(surfaces=[],delegate=null){this.surfaces=surfaces.map(s=>({...s,point:asVec(s.point),normal:asVec(s.normal).normalize()}));this.delegate=delegate}
  raycast(origin,direction,maxDistance=100){const o=asVec(origin),d=asVec(direction).normalize();if(this.delegate){const hit=this.delegate(origin,direction,maxDistance);if(hit==null)return null;if(!Number.isFinite(hit.distance)||!hit.point||!hit.normal)throw new TypeError('authored raycast hit requires distance, point, normal');return {...hit,distance:Number(hit.distance),point:asVec(hit.point),normal:asVec(hit.normal).normalize()}}let best=null;for(const s of this.surfaces){const denom=d.dot(s.normal);if(Math.abs(denom)<1e-9)continue;const t=s.point.sub(o).dot(s.normal)/denom;if(t>=0&&t<=maxDistance&&(!best||t<best.distance))best={surfaceId:s.id,distance:t,point:o.add(d.mul(t)),normal:s.normal.clone(),room:s.room??null,zones:s.zones??[]}}return best}
}
function cloneBody(b){return new BodyState({position:b.position.clone(),velocity:b.velocity.clone(),orientation:b.orientation.clone(),angularVelocity:b.angularVelocity.clone(),mass:b.mass,radius:b.radius,damping:b.damping,drag:b.drag})}
export class SensorFrame {
  constructor({body,contact,room,zones=[],down}){this.version='sensor-1';this.proprioception={position:body.position.toJSON(),velocity:body.velocity.toJSON(),speed:body.velocity.length(),provenance:MODELLED};this.contact={grounded:Boolean(contact?.grounded),phase:contact?.phase??'AIRBORNE',normal:contact?.normal??null,provenance:MODELLED};this.rays={down:{distance:down?.distance??null,hit:down?.surfaceId??null,normal:down?.normal?.toJSON?.()??null,provenance:MODELLED}};this.environment={room:room??null,coarseZones:zones,provenance:Object.freeze({...MODELLED,units:'room/zone ids'})};this.channels={vision:{status:'UNAVAILABLE',value:null,provenance:Object.freeze({...MODELLED,units:'ray samples',samplingFrequencyHz:0,limitations:['coarse authored visual-ray adapter not configured'],confidence:0,sourceReferences:[]})},olfaction:{status:'UNAVAILABLE',value:null,provenance:Object.freeze({...MODELLED,units:'n/a',samplingFrequencyHz:0,limitations:['no olfactory adapter'],confidence:0,sourceReferences:[]})},taste:{status:'UNAVAILABLE',value:null,provenance:Object.freeze({...MODELLED,units:'n/a',samplingFrequencyHz:0,limitations:['no taste adapter'],confidence:0,sourceReferences:[]})},airflow:{status:'UNAVAILABLE',value:null,provenance:Object.freeze({...MODELLED,units:'m/s',samplingFrequencyHz:0,limitations:['no airflow adapter'],confidence:0,sourceReferences:[]})},temperature:{status:'UNAVAILABLE',value:null,provenance:Object.freeze({...MODELLED,units:'K',samplingFrequencyHz:0,limitations:['no temperature adapter'],confidence:0,sourceReferences:[]})},humidity:{status:'UNAVAILABLE',value:null,provenance:Object.freeze({...MODELLED,units:'1',samplingFrequencyHz:0,limitations:['no humidity adapter'],confidence:0,sourceReferences:[]})}};this.provenance=Object.freeze({proprioception:MODELLED,contact:MODELLED,rays:MODELLED,environment:Object.freeze({...MODELLED,units:'room/zone ids'}),channels:MODELLED})
  }
}
export class FlySimulation {
  constructor(environment,{fixedDt=.02,gravity=new Vec3(0,-9.81,0),rngState=0,downDirection=environment?.downDirection??new Vec3(0,-1,0)}={}){if(!environment?.hash||!environment?.schemaVersion)throw new TypeError('environment hash and schema required');this.environment=environment;this.fixedDt=fixedDt;this.gravity=gravity;this.downDirection=asVec(downDirection).normalize();this.upDirection=this.downDirection.mul(-1);this.physicsCollisionAdapter=new AuthoredSurfaceAdapter(environment.surfaces??[],environment.raycast);this.registry=new Map();this.time=0;this.tick=0;this.paused=false;this.rngState={seed:rngState};this.environmentState=environment.dynamicState??{};this.provenance=Object.freeze({physics:MODELLED,collision:Object.freeze({...MODELLED,units:'authored surface/raycast'}),sensors:MODELLED})}
  addFly({flyId,body=new BodyState(),provenance=MODELLED}){if(!flyId||this.registry.has(flyId))throw new Error('flyId must be unique');this.registry.set(flyId,{flyId,body:cloneBody(body),motors:{thrust:0,pitch:0,yaw:0,roll:0},room:null,zones:[],contact:{phase:'AIRBORNE',grounded:false,surfaceId:null,normal:null},sensors:null,sensorHistory:[],provenance:validateProvenance(provenance)});this.#sense(this.registry.get(flyId))}
  getFly(id){const f=this.registry.get(id);if(!f)throw new Error('unknown flyId');return f} listFlyIds(){return [...this.registry.keys()]}
  setMotors(id,motors){const f=this.getFly(id);f.motors={thrust:n(motors?.thrust),pitch:n(motors?.pitch),yaw:n(motors?.yaw),roll:n(motors?.roll)}}
  pause(){this.paused=true;return this} resume(){this.paused=false;return this}
  step(dt=this.fixedDt){if(this.paused)return this;return this.stepOne(dt)}
  stepOne(dt=this.fixedDt){if(!(dt>=0))throw new RangeError('dt');for(const f of this.registry.values()){const start=f.body.position.clone();f.body.applyThrust(this.upDirection.mul(f.motors.thrust));f.body.applyTorque(new Vec3(f.motors.roll,f.motors.yaw,f.motors.pitch));f.body.integrate(dt,this.gravity);let contact=null;for(const s of this.physicsCollisionAdapter.surfaces){const n=s.normal, before=start.sub(s.point).dot(n), after=f.body.position.sub(s.point).dot(n), limit=f.body.radius;if(after<limit&&(before>=limit||f.body.velocity.dot(n)<0)){f.body.position=f.body.position.add(n.mul(limit-after));const inward=f.body.velocity.dot(n);if(inward<0)f.body.velocity=f.body.velocity.sub(n.mul(inward));contact={phase:(Math.abs(f.body.velocity.dot(n))<.02&&n.dot(this.upDirection)>.5)?'STABLE_REST':'LANDED',grounded:n.dot(this.upDirection)>.5,surfaceId:s.id,normal:n.toJSON()}}}const hit=this.physicsCollisionAdapter.raycast(f.body.position,this.downDirection,Math.max(1,f.body.radius*4));if(!contact&&hit){const height=f.body.position.sub(hit.point).dot(this.upDirection);if(height<=f.body.radius){f.body.position=hit.point.add(this.upDirection.mul(f.body.radius));const normalVelocity=f.body.velocity.dot(this.upDirection);if(normalVelocity<0)f.body.velocity=f.body.velocity.sub(this.upDirection.mul(normalVelocity));contact={phase:Math.abs(f.body.velocity.dot(this.upDirection))<.02?'STABLE_REST':'LANDED',grounded:true,surfaceId:hit.surfaceId,normal:hit.normal?.toJSON?.()??null}}}f.contact=contact??{phase:'AIRBORNE',grounded:false,surfaceId:null,normal:null};f.room=this.environment.roomAt?.(f.body.position)??hit?.room??null;f.zones=this.environment.zonesAt?.(f.body.position)??hit?.zones??[];this.#sense(f)}this.time+=dt;this.tick+=1;return this}
  stepN(count){const steps=Math.max(0,Math.floor(count));for(let i=0;i<steps;i++)this.stepOne();return this}
  telemetrySnapshot(flyId,{lagSeconds=0,controller='HEURISTIC TEST CONTROLLER',checkpointStatus}={}){const f=this.getFly(flyId),b=f.body;return {tick:this.tick,time:this.time,timeSeconds:this.time,flyId:f.flyId,fly:{id:f.flyId},transform:{position:b.position.toJSON(),orientation:b.orientation.toJSON()},velocity:{linear:b.velocity.toJSON(),angular:b.angularVelocity.toJSON(),speed:b.velocity.length()},contact:{...f.contact},room:f.room,zones:[...f.zones],sensorSummary:{version:f.sensors?.version??null,proprioception:f.sensors?.proprioception??null,channels:Object.fromEntries(Object.entries(f.sensors?.channels??{}).map(([k,v])=>[k,{status:v.status}]))},controller:{name:controller},provenance:{fly:f.provenance,physics:this.provenance.physics,sensors:this.provenance.sensors},motor:{...f.motors},checkpointStatus:checkpointStatus??{version:'checkpoint-1',environmentHash:this.environment.hash,environmentSchema:this.environment.schemaVersion,glbHash:this.environment.glbHash??null,lagSeconds}}}
  #sense(f){const down=this.physicsCollisionAdapter.raycast(f.body.position,this.downDirection,100);f.sensors=new SensorFrame({body:f.body,contact:f.contact,room:f.room,zones:f.zones,down});f.sensorHistory.push(f.sensors);if(f.sensorHistory.length>32)f.sensorHistory.shift()}
  checkpoint(){return checkpoint(this)}
}
export class FixedStepScheduler {constructor(sim,{onStep=()=>{}}={}){this.sim=sim;this.onStep=onStep;this.lag=0;this.running=false;this.frame=null;this.lastWallTime=null;this.requestFrame=null;this.cancelFrame=null;this.processingTimeSeconds=0;this.cannotKeepPace=false}recordProcessing(seconds){this.processingTimeSeconds=seconds;this.cannotKeepPace=seconds>this.sim.fixedDt}manualStep(count=1){for(let i=0;i<count;i++){this.sim.stepOne(this.sim.fixedDt);this.onStep(this.sim)}return count}advanceWallClock(seconds){this.lag+=Math.max(0,seconds);const count=Math.floor((this.lag+1e-12)/this.sim.fixedDt);for(let i=0;i<count;i++){this.sim.stepOne(this.sim.fixedDt);this.onStep(this.sim)}this.lag=Math.max(0,this.lag-count*this.sim.fixedDt);return count}start({now=()=>performance.now()/1000,requestFrame=globalThis.requestAnimationFrame,cancelFrame=globalThis.cancelAnimationFrame}={}){if(this.running)return this;this.running=true;this.requestFrame=requestFrame;this.cancelFrame=cancelFrame;this.lastWallTime=null;const frame=(timestamp)=>{if(!this.running)return;const current=Number.isFinite(timestamp)?timestamp/1000:now();if(this.lastWallTime!==null)this.advanceWallClock(current-this.lastWallTime);this.lastWallTime=current;this.frame=typeof this.requestFrame==='function'?this.requestFrame(frame):null};this.frame=typeof requestFrame==='function'?requestFrame(frame):null;return this}stop(){this.running=false;if(this.frame!=null&&typeof this.cancelFrame==='function')this.cancelFrame(this.frame);this.frame=null;return this}status(){return {running:this.running,fixedDt:this.sim.fixedDt,lagSeconds:this.lag,stepsBehind:Math.floor(this.lag/this.sim.fixedDt),cannotKeepPace:this.cannotKeepPace,processingTimeSeconds:this.processingTimeSeconds,silentDrops:0}}}
export class HeuristicTestController {constructor(){this.name='HEURISTIC TEST CONTROLLER'}motorFromSensor(sensor){return {thrust:sensor.contact.grounded?12:0,pitch:0,yaw:0,roll:0}}}
const telemetryKeys=new Set(['flyId','sequence','state','metadata','lag']);
export class TelemetryLagError extends Error {constructor(){super('telemetry lag exceeds configured limit');this.name='TelemetryLagError'}}
export class TelemetryProtocol {encode(frame){if(!frame||Object.keys(frame).some(k=>!telemetryKeys.has(k)))throw new TypeError('telemetry allowlist');if(!frame.flyId)throw new TypeError('telemetry flyId required');const state=frame.state??{};if(Object.keys(state).some(k=>!['room','position','orientation','contact'].includes(k)))throw new TypeError('telemetry state allowlist');return JSON.stringify({version:'telemetry-1',flyId:String(frame.flyId),sequence:Number.isInteger(frame.sequence)?frame.sequence:0,state:{room:state.room??null,position:state.position??null,orientation:state.orientation??[0,0,0,1],contact:state.contact??null},metadata:{controller:frame.metadata?.controller??'HEURISTIC TEST CONTROLLER',provenance:frame.metadata?.provenance??'MODELLED',units:frame.metadata?.units??'SI'},lag:frame.lag??0})}}
export class WebSocketTelemetryAdapter {constructor(socket,protocol=new TelemetryProtocol(),{maxLag=Infinity}={}){this.socket=socket;this.protocol=protocol;this.maxLag=maxLag}send(frame){const lag=frame.lag===undefined&&this.maxLag===0?1:frame.lag??0;if(lag>this.maxLag)throw new TelemetryLagError();this.socket.send(this.protocol.encode({...frame,lag}));return true}}
const canonical=(x)=>JSON.stringify(x,(k,v)=>v instanceof Vec3||v instanceof Quat?v.toJSON():v);const digest=(x)=>{let h=2166136261;for(const c of canonical(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')};
const cloneJson=(x)=>JSON.parse(JSON.stringify(x));
export function checkpoint(sim){return cloneJson({version:'checkpoint-1',environmentHash:sim.environment.hash,glbHash:sim.environment.glbHash??null,environmentSchema:sim.environment.schemaVersion,time:sim.time,tick:sim.tick,rngState:sim.rngState,sensorHistory:[...sim.registry.values()].map(f=>({flyId:f.flyId,history:f.sensorHistory})),environmentState:sim.environmentState,flies:[...sim.registry.values()].map(f=>({flyId:f.flyId,body:f.body.toJSON(),motors:f.motors,room:f.room,zones:f.zones,contact:f.contact,provenance:f.provenance}))})}
export function restore(sim,cp){if(cp.version!=='checkpoint-1')throw new Error('checkpoint version');if(cp.environmentHash!==sim.environment.hash)throw new Error('environment hash mismatch');if((cp.glbHash??null)!==(sim.environment.glbHash??null))throw new Error('GLB hash mismatch');if(cp.environmentSchema!==sim.environment.schemaVersion)throw new Error('environment schema mismatch');sim.registry.clear();for(const f of cp.flies)sim.addFly({flyId:f.flyId,body:new BodyState(f.body),provenance:f.provenance});for(const f of cp.flies){const live=sim.getFly(f.flyId);live.motors=f.motors;live.room=f.room;live.zones=f.zones;live.contact=f.contact;live.sensorHistory=cp.sensorHistory?.find(x=>x.flyId===f.flyId)?.history??[];live.sensors=live.sensorHistory.at(-1)??live.sensors}sim.time=cp.time;sim.tick=cp.tick??Math.round(sim.time/sim.fixedDt);sim.rngState=cp.rngState;sim.environmentState=cp.environmentState;return sim}
export function replay(sim,events=[]){for(const event of events){if(event.dt!==undefined&&Math.abs(event.dt-sim.fixedDt)>1e-12)throw new RangeError('replay requires fixed dt');for(const [id,motors] of Object.entries(event.inputs??{}))sim.setMotors(id,motors);sim.step(sim.fixedDt)}return sim}
export function stateHash(sim){return digest(checkpoint(sim))} export function replayHash(simOrEvents,maybeEvents){return digest({version:'replay-1',initial:simOrEvents instanceof FlySimulation?stateHash(simOrEvents):null,events:maybeEvents??simOrEvents})}
export function createFlyWorldEnvironmentAdapter(environment){if(!environment||typeof environment.raycast!=='function')throw new TypeError('authored environment raycast required');const hash=String(environment.environmentHash??environment.hash??'fly-world-authored');return Object.freeze({hash,glbHash:environment.glbHash==null?null:String(environment.glbHash),schemaVersion:String(environment.schemaVersion??'fly-world-environment'),downDirection:asVec(environment.downDirection??[0,-1,0]),raycast:(o,d,m)=>{const hit=environment.raycast(o,d,m);if(hit==null)return null;if(!Number.isFinite(hit.distance)||!hit.point||!hit.normal)throw new TypeError('authored raycast hit requires distance, point, normal');return {...hit,point:asVec(hit.point),normal:asVec(hit.normal).normalize()};},roomAt:environment.roomAt,zonesAt:environment.zonesAt,dynamicState:environment.dynamicState??null})}
export class SpectatorBridge {constructor({now=()=>Date.now()}={}){this.now=now;this.authority='spectator-read-only';this.sentCommands=0;this.frames=[];this.raf=null;this.lastSequence=-1;this.droppedFrames=0;this.lagStatus={lagSeconds:0,silentDrops:0}}ingest(frame){if(frame.version!=='telemetry-1'||!frame.state?.position)return false;if(Number.isInteger(frame.sequence)&&frame.sequence<=this.lastSequence){this.droppedFrames+=1;this.lagStatus={...this.lagStatus,silentDrops:this.droppedFrames};return false}this.lastSequence=frame.sequence??this.lastSequence;this.frames.push(frame);this.frames=this.frames.slice(-2);this.lagStatus={lagSeconds:frame.lag??0,silentDrops:this.droppedFrames};return true}render(target,alpha=.5){const [a,b]=this.frames;if(!b)return false;const t=Math.max(0,Math.min(1,alpha)),p=a.state.position.map((v,i)=>v+(b.state.position[i]-v)*t),qa=a.state.orientation??[0,0,0,1],qb=b.state.orientation??[0,0,0,1],q=qa.map((v,i)=>v+(qb[i]-v)*t),ql=Math.hypot(...q)||1;target.position?.set(...p);target.quaternion?.set?.(...q.map(v=>v/ql));return true}start(target,{requestFrame=globalThis.requestAnimationFrame}={}){if(typeof requestFrame!=='function')return;const tick=()=>{this.render(target,.5);this.raf=requestFrame(tick)};this.raf=requestFrame(tick)}stop(cancel=globalThis.cancelAnimationFrame){if(this.raf&&typeof cancel==='function')cancel(this.raf);this.raf=null}}
export function createBrowserSimulation(environment,options={}){const simulation=new FlySimulation(environment,options);return {simulation,bridge:new SpectatorBridge(options)}}
